Minor fix
smartcontractkit/chainlink pull request #10000
Opened 2023-07-31 15:44 UTC by bolekk

2023-07-31 15:47 UTC, RensR commented
@kaleofduty 😢

2023-07-31 15:48 UTC, RensR requested changes
So we're never actually going to merge PR 10k 😮

2023-07-31 15:50 UTC, kaleofduty commented on core/services/chainlink/application.go
> +
can't believe we've been running all these years without this vital feature

2023-07-31 16:10 UTC, makramkd requested changes

2023-07-31 16:10 UTC, makramkd commented on core/services/chainlink/application.go
> +		panic("stop")
Nit / 💀  code `panic` after `os.Exit`

2023-07-31 16:31 UTC, bolekk commented on core/services/chainlink/application.go
> +		panic("stop")
Fixed!

2023-08-02 15:52 UTC, essamhassan commented on core/services/chainlink/application.go
> +	time.AfterFunc(time.Duration(24)*time.Hour, func() {
nit: do we want to pull this calc out?

2023-08-04 01:06 UTC, bolekk commented
See ya at 20k!

2023-08-04 01:06 UTC, closed without merging