RE-1535 - update ga dep to node v16
smartcontractkit/chainlink pull request #10138
Opened 2023-08-09 22:06 UTC by momentmaker

2023-08-09 22:40 UTC, chainchad requested changes

2023-08-09 22:40 UTC, chainchad commented on .github/actions/goreleaser-build-sign-publish/README.md
> +        uses: aws-actions/configure-aws-credentials@5fd3084fc36e372ff1fff382a39b10d03659f355 v2.2.0
```suggestion
        uses: aws-actions/configure-aws-credentials@5fd3084fc36e372ff1fff382a39b10d03659f355 # v2.2.0
```

2023-08-09 22:46 UTC, momentmaker commented on .github/actions/goreleaser-build-sign-publish/README.md
> +        uses: aws-actions/configure-aws-credentials@5fd3084fc36e372ff1fff382a39b10d03659f355 v2.2.0
ahh nice catch

2023-08-14 15:42 UTC, chainchad approved these changes

2023-08-15 14:39 UTC, merged