Bcf 2441 update loop interface
smartcontractkit/chainlink pull request #10349
Opened 2023-08-24 20:50 UTC by krehermann

2023-08-28 12:33 UTC, samsondav requested changes

2023-08-28 12:33 UTC, samsondav commented on core/chains/chain_set.go
>  }
Is this still used?

2023-08-28 12:33 UTC, samsondav commented on core/chains/solana/chain_test.go
> +	//lggr := logger.TestLogger(t)
?

2023-08-28 12:33 UTC, samsondav commented on core/chains/starknet/chain_set.go
> +// TODO rename to ChainOpts
include ticket # pls

2023-08-28 12:33 UTC, samsondav commented on core/chains/starknet/config.go
> +	// Do no access directly. Use IsEnabled
```suggestion
	// Do not access directly. Use IsEnabled
```

2023-08-28 12:33 UTC, samsondav commented on core/services/chainlink/relayer_factory.go
> +			// TODO change the solana loop toml deserializer so we can get rid of the singleChainCfg
all todos should have a ticket linked otherwise they tend to fall into the dustbin of history

2023-08-28 12:33 UTC, samsondav commented on core/services/chainlink/relayer_factory.go
> +				// this should not happen because the driving loop is supposed to skip disabled chains
maybe panic instead then?

2023-08-28 12:33 UTC, samsondav commented on core/services/chainlink/relayer_factory.go
> +// TODO consider consolidating the driving logic with that of NewSolana above via generics
see comment above re: ticket links in comments

2023-08-28 12:33 UTC, samsondav commented on core/services/relay/evm/relayer_extender_test.go
> +	assert.Equal(t, 0, cnt)
Why has this changed?

2023-08-28 12:33 UTC, samsondav commented on plugins/cmd/chainlink-solana/main.go
> +	// doesn't need `Configs`
ticket

2023-08-28 12:33 UTC, samsondav commented on plugins/cmd/chainlink-starknet/main.go
> +	// doesn't need `Configs`
ticket

2023-08-29 14:02 UTC, jmank88 commented on core/chains/evm/chain.go
> +	toml, err := c.cfg.TOMLString()
Same question here. Isn't `c.cfg` the global config, rather than just this chain?

2023-08-29 14:04 UTC, jmank88 commented on core/web/solana_chains_controller_test.go
> +Enabled = true
Why did this change? Just to expand coverage?

2023-08-30 12:55 UTC, jmank88 commented
nit/ The branch is prefixed as `BCF-2441-` - will this confuse Jira?

2023-08-30 17:34 UTC, jmank88 approved these changes

2023-08-30 17:55 UTC, jmank88 approved these changes

2023-08-30 19:12 UTC, samsondav approved these changes

2023-08-30 19:34 UTC, merged