Ensure txdb.conn is not closed on tx context cancelation
smartcontractkit/chainlink pull request #10935
Opened 2023-10-12 13:01 UTC by dhaidashenko

txdb.conn implements driver.Validation & driver.SessionResetter to prevent database/sql from closing connection if context of transaction was cancelled

2023-10-12 13:08 UTC, jmank88 approved these changes

2023-10-12 14:32 UTC, amit-momin approved these changes

2023-10-12 14:38 UTC, krehermann requested changes
there is a TODO in BeginTx: //TODO: Fix context handling

is the that same problem you are trying to solve here? if so, can you move the comment out of the test and into that func to explain why ctx is ignored?

2023-10-13 10:52 UTC, dhaidashenko commented
> there is a TODO in BeginTx: //TODO: Fix context handling
> 
> is the that same problem you are trying to solve here? if so, can you move the comment out of the test and into that func to explain why ctx is ignored?

No, it's a different problem, but I've improved comment in the BeginTx. 
BeginTx has roughly following call stack: sqlx.BeginTx -> database/sql.BeginTx -> pgtest.BeginTx
Fix addresses how database/sql treats tx's connection when context in canceled
 > BeginTx: //TODO: Fix context handling
 Refers to handling context in the pgtest.BeginTx. But It does not make sense with current design as we have single tx shared among all of the callers. So I removed it

2023-10-13 12:31 UTC, krehermann approved these changes

2023-10-13 13:12 UTC, merged