Fix redundant "replacing abandoned tx" logs
smartcontractkit/chainlink pull request #11019
Opened 2023-10-20 12:04 UTC by mohamed-mehany

### Description

This fixes the issue of incorrectly logging the "replacing abandoned tx" log. 
The DELETE query doesn't return a sql.ErrNoRows on failing to find rows to be deleted. Instead we are checking on the count of RowsAffected. 
Another minor fix is continuing to execute the function if no attempts were deleted, instead of throwing an error, since at this point there is no need to break the execution flow.

### Context
[BCI-2320](https://smartcontract-it.atlassian.net/browse/BCI-2320)

2023-10-20 18:46 UTC, simsonraj requested changes
Please add tests for the new logic

2023-10-23 10:17 UTC, prashantkumar1982 reviewed
Looks good. Just add a unit-test as Simson commented.

2023-10-24 12:51 UTC, mohamed-mehany commented
I've discussed offline with @simsonraj.
We concluded that more tests are not required since the main logic (actual replacement of abandoned transaction and transition to in progress without replacement) is already covered by tests. 
The remaining uncovered 3 lines (logs and exception) are not easily testable with our testing setup.

cc: @prashantkumar1982

2023-10-24 14:04 UTC, prashantkumar1982 approved these changes

2023-10-25 08:57 UTC, simsonraj approved these changes

2023-10-25 09:15 UTC, merged