[TT-758] Fixes Upgrade Test
smartcontractkit/chainlink pull request #11589
Opened 2023-12-15 20:39 UTC by kalverra

2023-12-15 22:10 UTC, tateexon approved these changes

2023-12-15 22:12 UTC, AnieeG commented on integration-tests/go.mod
> +replace github.com/testcontainers/testcontainers-go => github.com/Tofel/testcontainers-go v0.0.0-20231130110817-e6fbf9498b56
Let's keep it with rest of the replaces

2023-12-15 22:12 UTC, AnieeG commented on integration-tests/migration/upgrade_version_test.go
> +	upgradeImage, err := osutil.GetEnv("TEST_UPGRADE_IMAGE")
why TEST ?

2023-12-15 22:22 UTC, AnieeG requested changes

2023-12-15 22:22 UTC, AnieeG commented on integration-tests/migration/upgrade_version_test.go
> +	upgradeImage, err := osutil.GetEnv("TEST_UPGRADE_IMAGE")
Is this intentional?

2023-12-18 15:45 UTC, AnieeG approved these changes

2023-12-18 16:21 UTC, AnieeG approved these changes

2023-12-18 16:45 UTC, merged