run compatibility tests also in nethermind
smartcontractkit/chainlink pull request #11816
Opened 2024-01-18 19:34 UTC by Tofel

2024-01-19 00:22 UTC, jmank88 submitted a review, later dismissed

2024-01-24 19:53 UTC, kalverra requested changes

2024-01-24 19:53 UTC, kalverra commented on .github/workflows/client-compatibility-tests.yml
> +          test_command_to_run: ./tests -test.timeout ${{ matrix.timeout }} -test.parallel=2 -test.run ${{ matrix.test }}
```suggestion
          test_command_to_run: ./tests -test.timeout ${{ matrix.timeout }} -test.run ${{ matrix.test }}
```
We don't need this anymore if we intend on only running 1 test.

2024-01-24 19:57 UTC, kalverra approved these changes

2024-01-24 21:49 UTC, merged