Tt 791 seth ocr tests
smartcontractkit/chainlink pull request #12076
Opened 2024-02-19 14:16 UTC by Tofel

2024-02-27 18:05 UTC, kalverra requested changes

2024-02-27 18:05 UTC, kalverra commented on integration-tests/actions/seth/refund.go
I like the interface approach to clean up the fund returning.

2024-02-27 18:05 UTC, kalverra commented on integration-tests/scripts/check_base64_env_var.sh
👍

2024-02-27 18:16 UTC, Tofel commented on integration-tests/actions/seth/actions.go
> +	nonce, err := client.Client.PendingNonceAt(ctx, fromAddress)
We have not, my man, but it's a very good call out. As I understand we want to add round-robing RPC node failover that would address this issue (provided that at least one node is synced).

2024-02-27 18:18 UTC, Tofel commented on integration-tests/actions/seth/actions.go
> +	gasLimit := uint64(client.Cfg.Network.TransferGasFee)
good catch, this might be copilot's hallucination!

2024-02-27 18:19 UTC, Tofel commented on integration-tests/actions/seth/actions.go
> +	t *testing.T,
I'd rather not... I have a separate ticket for later, where I want to unify local/non-local helpers, so maybe there I could also rip out `t`?

2024-02-27 18:19 UTC, Tofel commented on integration-tests/actions/seth/actions.go
> +	for {
dat is indeed a very cool pattern!

2024-02-27 18:21 UTC, Tofel commented on integration-tests/actions/seth/actions.go
> +	getTransmitterAndPayeesFn func() ([]string, []string, error),
I thought that this way we don't have copy & paste or encapsulate in yet another method the different codes that retrieve these addresses from nodes or forwarder contracts

2024-02-27 18:21 UTC, Tofel commented on integration-tests/actions/seth/refund.go
I thought it would allow us to easily extend it without modifying any other retrying strategies

2024-02-27 20:50 UTC, skudasov commented on integration-tests/actions/seth/actions.go
> +	for {
Or we can use `avast.Retry`

2024-02-28 13:45 UTC, kalverra approved these changes

2024-02-28 16:18 UTC, skudasov approved these changes

2024-02-28 18:09 UTC, merged