set the foundation for v2.3 contracts
smartcontractkit/chainlink pull request #12255
Opened 2024-03-01 00:35 UTC by shileiwill

As title.

2024-03-01 19:00 UTC, RyanRHall requested changes

2024-03-01 19:09 UTC, shileiwill commented on contracts/src/v0.8/automation/dev/v2_3/README.md
> +
yes, makes sense. this is version (at least minor version) agnostic.

2024-03-01 19:26 UTC, shileiwill commented on core/gethwrappers/generated/i_automation_registry_master_wrapper_2_2/i_automation_registry_master_wrapper_2_2.go
> +type AutomationRegistryBase23OnchainConfig struct {
hmm, this definitely doesnt seem right. let me dig in.

2024-03-01 20:20 UTC, shileiwill commented on core/gethwrappers/generated/i_automation_registry_master_wrapper_2_2/i_automation_registry_master_wrapper_2_2.go
> +type AutomationRegistryBase23OnchainConfig struct {
ok, this is bc both v2.2 and v2.3 use the same name for IAutomationRegistryMaster. Now I named v2.3 to IAutomationRegistryMaster2_3

2024-03-04 17:00 UTC, RyanRHall commented on contracts/src/v0.8/automation/dev/v2_3/AutomationRegistrar2_3.sol
> +   *                          Add native billing and ERC20 billing support
👍

2024-03-04 17:21 UTC, shileiwill commented on contracts/src/v0.8/automation/README.md
> +- We use Logic A, B, C... to avoid confusion with the version ex `AutomationRegistryLogicA2_2.sol` --> Logic Contract A verion 2.1
haha, sharp eyes! It turns out to be an old one from v2.2, https://github.com/smartcontractkit/chainlink/blob/develop/contracts/src/v0.8/automation/dev/v2_2/README.md

2024-03-04 23:15 UTC, RyanRHall approved these changes

2024-03-19 21:10 UTC, closed without merging