fixed evm client flake
smartcontractkit/chainlink pull request #12376
Opened 2024-03-11 16:38 UTC by dhaidashenko

2024-03-11 17:21 UTC, jmank88 requested changes
This kind of things is generally not mentioned in the changelog since it is just noise to node operators. @HenryNguyen5 @momentmaker  are we changing our policy here?

2024-03-11 17:23 UTC, dimriou commented on .changeset/dry-fishes-hang.md
Is this new?

2024-03-11 17:34 UTC, jmank88 approved these changes

2024-03-11 17:48 UTC, HenryNguyen5 commented
> This kind of things is generally not mentioned in the changelog since it is just noise to node operators. @HenryNguyen5 @momentmaker are we changing our policy here?

AFAIK we don't include changes to tests in changelogs. They don't have anything to do with the application itself.

@smartcontractkit/releng can you comment on this? I'm not up to date on our policy

2024-03-12 01:46 UTC, prashantkumar1982 approved these changes

2024-03-12 02:17 UTC, merged