Pipeline Data Corruption
smartcontractkit/chainlink pull request #13286
Opened 2024-05-21 22:24 UTC by EasterTheBunny

The unit test `TestDivide_Example` was acting flakey in the CI pipeline which suggested a flaw in the divide and multiply operations. When running the test, the expected result would be one of the input values or the division result in failure cases. This implied that results were either received out of order or were being sorted incorrectly.

The pipeline runner does a final sort on the results, so that ruled out the out of order possibility. On inspection of the sorting index on each task, every index was the zero value. This resulted in occasional correct and incorrect sorting, causing the test flake.

To correct the problem, task indexes are now set within the `Parse` function and a new unit test ensure the indexes are set properly.

2024-05-21 22:40 UTC, jmank88 submitted a review, later dismissed

2024-05-22 12:48 UTC, samsondav requested changes
Can we add some checks to this to prevent being able to parse a pipeline with ambiguous ordering?

2024-05-22 16:59 UTC, jmank88 approved these changes, later dismissed

2024-05-22 17:13 UTC, samsondav approved these changes, later dismissed
Technically a breaking change and should be marked as such, but since the behaviour if you mixed and matched unspecified+0 index was undefined anyway, it shouldn't affect anything

2024-05-22 17:49 UTC, samsondav approved these changes

2024-05-22 17:54 UTC, vyzaldysanchez approved these changes

2024-05-22 18:10 UTC, merged