[TT-1128] remove evm client usages
smartcontractkit/chainlink pull request #13568
Opened 2024-06-17 07:33 UTC by Tofel

2024-06-18 10:14 UTC, gheorghestrimtu submitted a review, later dismissed

2024-06-18 13:49 UTC, kalverra requested changes

2024-06-18 13:49 UTC, kalverra commented on integration-tests/README_SETH.md
> +You can find sample code for doing that for LINK token in [actions.(./actions/seth/actions.go) file as `SendLinkFundsToDeploymentAddresses()` method.
Seems this was a casualty of the find-replace
```suggestion
You can find sample code for doing that for LINK token in [actions](./actions/actions.go) file as `SendLinkFundsToDeploymentAddresses()` method.
```

2024-06-19 12:36 UTC, kalverra approved these changes, later dismissed

2024-06-19 13:10 UTC, gheorghestrimtu approved these changes

2024-06-19 13:13 UTC, kalverra approved these changes

2024-06-19 13:30 UTC, merged