re-enable v2 test
smartcontractkit/chainlink pull request #13656
Opened 2024-06-21 18:06 UTC by krehermann

[MERC-5697](https://smartcontract-it.atlassian.net/browse/MERC-5697)
  
  missed test re-enablement in https://github.com/smartcontractkit/chainlink/commit/b584df5c4f99a9e2c8734959a40cf730bbb1435a

### Requires Dependencies

### Resolves Dependencies

2024-06-21 18:30 UTC, jmank88 approved these changes

2024-06-23 22:11 UTC, jmank88 requested changes

2024-06-23 22:11 UTC, jmank88 commented on core/services/ocr2/plugins/mercury/integration_plugin_test.go
> -	integration_MercuryV1(t)
Is this an accidental deletion?

2024-06-24 23:55 UTC, krehermann commented on core/services/ocr2/plugins/mercury/integration_plugin_test.go
> -	integration_MercuryV1(t)
yes, thank you.

2024-06-25 09:34 UTC, DeividasK approved these changes

2024-06-25 15:10 UTC, jmank88 approved these changes

2024-06-25 17:59 UTC, merged