[TT-1304] try CTF with newer eth genesis generator and prysm versions
smartcontractkit/chainlink pull request #13669
Opened 2024-06-24 15:04 UTC by Tofel

2024-06-25 16:23 UTC, gheorghestrimtu approved these changes

2024-06-25 21:19 UTC, tateexon approved these changes

2024-06-25 21:20 UTC, tateexon requested changes
We should get a proper CTF version to merge first

2024-06-26 08:59 UTC, gheorghestrimtu approved these changes, later dismissed

2024-06-26 17:40 UTC, gheorghestrimtu approved these changes

2024-06-26 18:03 UTC, tateexon approved these changes

2024-06-27 08:43 UTC, merged