Move block rate and log limit into toml config
smartcontractkit/chainlink pull request #13700
Opened 2024-06-26 17:45 UTC by ferglor

https://smartcontract-it.atlassian.net/browse/AUTO-10027

In this PR, we are:

- Specifying defaults for the automatioin block rate and log limit in the toml config, based on the existing hard coded values [here](https://github.com/smartcontractkit/chainlink/blob/8863e3535f4c67f00fe6b380132bf72d78141215/core/services/ocr2/plugins/ocr2keeper/evmregistry/v21/logprovider/factory.go#L86)
- Cleaning up the old hard coded defaults
- Updating the oc2 config types in code to supply these new values

2024-06-27 18:01 UTC, ogtownsend approved these changes, later dismissed

2024-06-28 17:54 UTC, FelixFan1992 commented on core/chains/evm/config/toml/defaults/Polygon_Zkevm_Goerli.toml
this one is deprecated

2024-06-28 17:54 UTC, FelixFan1992 commented on core/chains/evm/config/toml/defaults/Polygon_Mumbai.toml
this one is deprecated

2024-06-28 17:54 UTC, FelixFan1992 commented on core/chains/evm/config/toml/defaults/Optimism_Goerli.toml
this one is deprecated

2024-06-28 17:54 UTC, FelixFan1992 commented on core/chains/evm/config/toml/defaults/Ethereum_Rinkeby.toml
this one is deprecated

2024-06-28 17:54 UTC, FelixFan1992 commented on core/chains/evm/config/toml/defaults/Ethereum_Goerli.toml
this one is deprecated

2024-06-28 17:54 UTC, FelixFan1992 commented on core/chains/evm/config/toml/defaults/Base_Goerli.toml
this one is deprecated

2024-06-28 17:54 UTC, FelixFan1992 commented on core/chains/evm/config/toml/defaults/Arbitrum_Goerli.toml
this one is deprecated

2024-06-28 17:55 UTC, FelixFan1992 commented on core/chains/evm/config/toml/defaults/fallback.toml
can we also update for zksync and gnosis(xdai)?

2024-07-05 10:21 UTC, infiloop2 requested changes
We also have this config values through ocr offchain config which overrides these, not fully sure if these should within toml config also, will add to confusion. 

one way to reduce confusion could be to name these as "FallbackBlockRate" and "FallbackLogLimit", but we should also think through why hardcoded values are not sufficient

2024-07-05 12:33 UTC, ferglor commented
> We also have this config values through ocr offchain config which overrides these, not fully sure if these should within toml config also, will add to confusion.
> 
> one way to reduce confusion could be to name these as "FallbackBlockRate" and "FallbackLogLimit", but we should also think through why hardcoded values are not sufficient

I'm happy to keep the hardcoded values (means we can just close this PR!), but my understanding was that we should have default values per chain set in the toml config, is that not the case?

2024-07-05 13:25 UTC, infiloop2 commented
keeping in toml might still be ok, but at least we should make it clear that these are only fallback values. I don't think we've had config yet which lives in both toml and offchain config yet so I would say discuss with @anirudhwarrier what would make sense here. (e.g. for new chains do we update toml or offchain config or both?)

2024-07-05 15:37 UTC, ferglor commented
> keeping in toml might still be ok, but at least we should make it clear that these are only fallback values. I don't think we've had config yet which lives in both toml and offchain config yet so I would say discuss with @anirudhwarrier what would make sense here. (e.g. for new chains do we update toml or offchain config or both?)

Discussed with @anirudhwarrier and he's okay with scrapping this PR and relying on the defaults in code; is that okay with you @infiloop2 ?

2024-07-05 15:39 UTC, anirudhwarrier commented
> keeping in toml might still be ok, but at least we should make it clear that these are only fallback values. I don't think we've had config yet which lives in both toml and offchain config yet so I would say discuss with @anirudhwarrier what would make sense here. (e.g. for new chains do we update toml or offchain config or both?)

After reconsidering this,  I think TOML config is overkill for a fallback config. I think this change should be discarded.

2024-07-08 11:17 UTC, closed without merging