Initial Impl of SBRV
smartcontractkit/chainlink pull request #13813
Opened 2024-07-10 17:48 UTC by Fletch153

2024-07-15 12:10 UTC, ad0ll commented on contracts/src/v0.8/llo-feeds/v0.4.0/DestinationVerifierProxy.sol
> + * The verifier proxy contract is the gateway for all report verification requests
Would recommend tweaking description to describe that this is a destination contract + destination behavior.

2024-07-22 21:01 UTC, ad0ll commented on contracts/src/v0.8/llo-feeds/v0.4.0/interfaces/IDestinationVerifier.sol
> +    uint8 f,
Just want to make sure, is f something we set? I thought I remember it was calculated from the OCR paper, although I can't remember if you can optionally set a number > the minimum

2024-07-22 21:07 UTC, ad0ll commented on contracts/src/v0.8/llo-feeds/v0.4.0/interfaces/IDestinationVerifierProxy.sol
> +   * @param payloads The encoded payloads to be verified, including the signed
Is this comment still accurate? I thought the VerifierProxy docs would closely match the Verifier docs. Is what we're doing in the Verifier still considered routing?

2024-07-23 19:52 UTC, ad0ll commented on contracts/src/v0.8/llo-feeds/v0.4.0/DestinationVerifier.sol
> +  function getAccessController() external view override returns (address) {
Is there a reason to have this function be called getAccessController instead of s_accessController() like it is in the VerifierProxy?

2024-07-23 19:52 UTC, ad0ll commented on contracts/src/v0.8/llo-feeds/v0.4.0/DestinationVerifier.sol
> +  function getFeeManager() external view override returns (address) {
Same question as getAccessController()

2024-07-23 20:01 UTC, ad0ll commented on contracts/src/v0.8/llo-feeds/v0.4.0/interfaces/IDestinationVerifier.sol
> +  function setConfigActive(uint256 DONConfigID, bool isActive) external;
Two notes on this, strongly recommend used a camelcase variable name here, "donConfigId"

Second, would we break the interface if we added an _ to the beginning of the parameters like we have with setFeeManager and setAccessController (or if we removed it from _setFeeManager), would have to fix it in other functions too. I think it would be good to be consistent.

I personally use _ as a prefix to parameters when writing smart contracts myself, but don't feel strongly either way.

2024-07-23 20:05 UTC, ad0ll commented on contracts/src/v0.8/llo-feeds/v0.4.0/DestinationVerifier.sol
> +    address oldAccessController = address(s_accessController);
Is there a reason not to check interface compliance here like we do in the setFeeManager function?

2024-07-23 20:07 UTC, ad0ll commented on contracts/src/v0.8/llo-feeds/v0.4.0/DestinationVerifier.sol
> +    bytes24 DONConfigID;
suggest updating this to donConfigId  for consistent camelcase.

2024-07-29 12:56 UTC, Fletch153 commented on contracts/src/v0.8/llo-feeds/v0.4.0/interfaces/IDestinationVerifier.sol
> +    uint8 f,
'f' is something we set. It has a minimum of n/3 so if f is 5, there needs to be at least 16 signers, but technically a user could verify a report with 16 signatures, it just needs to > f

2024-07-29 12:58 UTC, Fletch153 commented on contracts/src/v0.8/llo-feeds/v0.4.0/DestinationVerifier.sol
> +  function getAccessController() external view override returns (address) {
Updated to make it more consistent

2024-07-29 13:08 UTC, Fletch153 commented on contracts/src/v0.8/llo-feeds/v0.4.0/DestinationVerifier.sol
> +    address oldAccessController = address(s_accessController);
AccessController doesn't implement the ERC165 method and i don't think it's worth updating tooling and other dependencies

2024-07-29 13:20 UTC, Fletch153 commented on contracts/src/v0.8/llo-feeds/v0.4.0/interfaces/IDestinationVerifier.sol
> +  function setConfigActive(uint256 DONConfigID, bool isActive) external;
_ is conventionally  used for internal functions and state variable shadowing. I've removed the incorrect use of the _ in the other functions.

Regarding DON prefix, unless you feel super strong about this then i think we should leave it as prefixing of Acronyms is usually down to preference. There's a few different variations of this variable name which could be correct.

2024-07-29 13:35 UTC, ad0ll requested changes

2024-07-29 13:35 UTC, ad0ll commented on contracts/src/v0.8/llo-feeds/v0.4.0/DestinationFeeManager.sol
> +  bytes32 private constant REPORT_V1 = 0x0001000000000000000000000000000000000000000000000000000000000000;
If this is for block number reports, any logic here can be completely removed (interface should still be compatible however). We have no plans at all to ever deploy block number based reports.

2024-07-29 13:35 UTC, ad0ll commented on contracts/src/v0.8/llo-feeds/v0.4.0/DestinationVerifier.sol
> +    Common.AddressAndWeight[] memory recipientAddressesAndWeights
Would it make sense to take advantage of this opportunity to remove this from the verifier and set it only in the feeManager? My thought is that if we do, we wouldn't have to put the recipientWeights in the verifier in RDD, one less step/complication w/ gauntlet

2024-07-29 13:35 UTC, ad0ll commented on contracts/src/v0.8/llo-feeds/v0.4.0/DestinationVerifier.sol
> +    i_verifierProxy = IDestinationVerifierProxy(verifierProxy);
Is this still necessary now that the destination verifier isn't calling the proxy?

2024-07-29 13:35 UTC, ad0ll commented on contracts/src/v0.8/llo-feeds/v0.4.0/DestinationVerifier.sol
> +    address oldAccessController = address(s_accessController);
We agreed that this is not worth the effort, esp since AccessController will likely be deprecated in the near future. Agreed to create Jira ticket w/ very low priority.

2024-07-29 13:35 UTC, ad0ll commented on contracts/src/v0.8/llo-feeds/v0.4.0/DestinationVerifier.sol
> +    Common.AddressAndWeight[] memory recipientAddressesAndWeights
Introduces too much complexity, can reevaluate when/if we streamline billing.

2024-07-29 13:35 UTC, ad0ll commented on contracts/src/v0.8/llo-feeds/v0.4.0/DestinationVerifier.sol
> +    i_verifierProxy = IDestinationVerifierProxy(verifierProxy);
https://github.com/smartcontractkit/chainlink/pull/13813/files/87e26436c59d242fd14f8e2ba7ab76635b5022ab#diff-6758803ce1c961e4be4aaefaf9465ed647f6794412704a99a16a155ff3f40061R350

It still is necessary for modifier checking that the caller is the verifier proxy, we don't want customers calling the verifier directly.

2024-07-29 13:37 UTC, ad0ll commented on contracts/src/v0.8/llo-feeds/v0.4.0/DestinationFeeManager.sol
> +  bytes32 private constant REPORT_V1 = 0x0001000000000000000000000000000000000000000000000000000000000000;
Auditors already have the code, we can fix this in a cleanup ticket later.

2024-07-29 18:50 UTC, samsondav submitted a review, later dismissed

2024-07-29 19:39 UTC, samsondav approved these changes, later dismissed

2024-07-31 01:07 UTC, ad0ll submitted a review, later dismissed

2024-07-31 10:43 UTC, samsondav approved these changes

2024-07-31 11:33 UTC, ad0ll approved these changes

2024-07-31 11:48 UTC, merged