use services.Engine
smartcontractkit/chainlink pull request #13851
Opened 2024-07-15 14:42 UTC by jmank88

### Requires Dependencies
- https://github.com/smartcontractkit/chainlink-common/pull/204

2024-08-01 23:37 UTC, krehermann approved these changes, later dismissed

2024-08-02 17:16 UTC, EasterTheBunny approved these changes, later dismissed

2024-08-05 14:19 UTC, EasterTheBunny submitted a review, later dismissed

2024-08-06 12:38 UTC, ilija42 requested changes

2024-08-06 12:38 UTC, ilija42 commented on core/chains/evm/monitor/balance.go
> +	bm.sleeperTask = utils.NewSleeperTask(&worker{bm: bm}) //TODO convert to sub-service?
Should this be a ticket?

2024-08-06 12:38 UTC, ilija42 commented on core/chains/evm/monitor/balance.go
Is this  `const ethFetchTimeout = 15 * time.Second` a relic before layer 2s and alt evm chains? Its out of scope but maybe we should raise this somewhere?

2024-08-06 12:38 UTC, ilija42 commented on core/chains/evm/monitor/balance.go
Sleeper task in common also times in 15seconds by default

2024-08-06 12:38 UTC, ilija42 commented on core/chains/evm/monitor/balance.go
>  func (bm *balanceMonitor) checkBalance(head *evmtypes.Head) {
also out of scope but may deserve a TODO. Looks like this should be called checkBalances and shouldn't accept any args

2024-08-06 12:38 UTC, ilija42 commented on core/recovery/recover.go
>  func WrapRecover(lggr logger.Logger, fn func()) {
What is the point of WrapRecover? I see all callers giving it a func for onPanic arg which then gets ignored

2024-08-06 12:38 UTC, ilija42 commented on core/services/fluxmonitorv2/flux_monitor.go
> +	fm.logger = logger.Sugared(fm.eng)
Is there a reason why we still need a logger outside of the one in the engine?

2024-08-06 12:38 UTC, ilija42 commented on core/services/nurse.go
> -func (n *Nurse) Close() error {
Maybe keep Close for the closing log

2024-08-06 12:38 UTC, ilija42 commented on core/services/nurse.go
> +func (n *Nurse) start(ctx context.Context) error {
ctx is unused here

2024-08-06 12:38 UTC, ilija42 commented on core/services/nurse.go
> +func (n *Nurse) start(ctx context.Context) error {
oh, I guess this is to satisfy the interface, maybe `start(_ context.Context) error {` then

2024-08-06 14:51 UTC, jmank88 commented on core/recovery/recover.go
>  func WrapRecover(lggr logger.Logger, fn func()) {
This variant does not have a custom onPanic arg, so it just logs critical.

2024-08-06 14:53 UTC, jmank88 commented on core/chains/evm/monitor/balance.go
Seems like it, but I also don't see any reason for this timeout to be related to block times at all. It is not as if the call would block until a block is produced. :confused:

2024-08-06 14:55 UTC, jmank88 commented on core/services/nurse.go
> -func (n *Nurse) Close() error {
The engine will already log

2024-08-06 14:56 UTC, jmank88 commented on core/services/fluxmonitorv2/flux_monitor.go
> +	fm.logger = logger.Sugared(fm.eng)
This type used sugared logger methods, so this is just creating it once.

2024-08-06 14:59 UTC, jmank88 commented on core/chains/evm/monitor/balance.go
> +	bm.sleeperTask = utils.NewSleeperTask(&worker{bm: bm}) //TODO convert to sub-service?
I think I can just drop it

2024-08-06 15:43 UTC, jmank88 commented on core/chains/evm/monitor/balance.go
https://smartcontract-it.atlassian.net/browse/BCI-3948

2024-08-06 15:48 UTC, ilija42 approved these changes

2024-08-06 21:38 UTC, EasterTheBunny approved these changes

2024-08-06 22:11 UTC, merged