Move chain agnostic sql types in core/store/models to chainlink-common/sqlutil/models
smartcontractkit/chainlink pull request #13881
Opened 2024-07-18 03:33 UTC by reductionista

This moves the chain agnostic db types into chainlink-common, and evm-specific types from models into models/evm to match models/solana & models/cosmos. (Soon, all of these should be moved into their respective relays.)

### Requires Dependencies

- https://github.com/smartcontractkit/chainlink-common/pull/665

2024-07-18 10:44 UTC, jmank88 commented
> models.Interval

Are other types used? Or just this one?

> This moves the chain agnostic db types into chainlink-common

I think this is too broad of a rule. Yes, common must remain chain agnostic, but it doesn't follow that everything chain agnostic should move to common. Core does a lot of chain-agnostic things that do not need to leak out of that module at all. Common is reserved for things that are common to everything.

2024-08-01 18:14 UTC, jmank88 requested changes
Please see my comment

2024-08-01 18:52 UTC, reductionista commented
> > models.Interval
> 
> Are other types used? Or just this one?
> 
> > This moves the chain agnostic db types into chainlink-common
> 
> I think this is too broad of a rule. Yes, common must remain chain agnostic, but it doesn't follow that everything chain agnostic should move to common. Core does a lot of chain-agnostic things that do not need to leak out of that module at all. Common is reserved for things that are common to everything.

Interval was the only one I needed for extracting ChainReader, but looking over the rest all of them except Cron looked like things that we'll probably need at some point to import from the relays. They should be available to any code that needs to read and write from a database where these types might be part of the schema. Otherwise, anyone who needs to add a column of one of these types (eg, JSON types or URL's) will be faced with the choice of duplicating their own custom types or having to raise a new PR to move them over into common. I can already guess that nobody is going to bother moving them if we don't put them there now, because it will be too big of a pain to do one at a time.

I think you have a point when it comes to the Cron type, it will probably only ever be needed by `chainlink` repo--we can leave that there, I just moved it with the rest since I figured it doesn't hurt and it's kind of weird moving everything but one type.

Here is the full list of types that are moved to common in this PR, for reference:
```
core/store/models/common.go:

// JSON stores the json types string, number, bool, and null.
// Arrays and Objects are returned as their raw json types.
type JSON struct {
       gjson.Result
}

// WebURL contains the URL of the endpoint.
type WebURL url.URL

// Cron holds the string that will represent the spec of the cron-job.
type Cron string

// Interval represents a time.Duration stored as a Postgres interval type
type Interval time.Duration

core/store/models/errors.go:

// JSONAPIErrors holds errors conforming to the JSONAPI spec.
type JSONAPIErrors struct {
       Errors []JSONAPIError `json:"errors"`
}

// JSONAPIError is an individual JSONAPI Error.
type JSONAPIError struct {
       Detail string `json:"detail"`
}

core/store/models/secrets.go:

// Secret is a string that formats and encodes redacted, as "xxxxx".
//
// Use Value to get the actual secret.
type Secret string
```

2024-08-01 19:17 UTC, reductionista commented
Oh, and it also moves this helper function from cltest to commontest, which is needed in order for the tests on the json types to run in chainilnk-common:
```
// JSONFromString create JSON from given body and arguments
func JSONFromString(t testing.TB, body string, args ...interface{}) models.JSON {
      return JSONFromBytes(t, []byte(fmt.Sprintf(body, args...)))
}

// JSONFromBytes creates JSON from a given byte array
func JSONFromBytes(t testing.TB, body []byte) models.JSON {
         j, err := models.ParseJSON(body)
       require.NoError(t, err)
       return j
}

func MustJSONMarshal(t *testing.T, val interface{}) string {
       t.Helper()
       bs, err := json.Marshal(val)
       require.NoError(t, err)
       return string(bs)
}
```
For the same reason, I expect these will be useful for many different repos to be able to import

2024-08-01 21:59 UTC, jmank88 commented
> things that we'll probably need at some point to import from the relays.

This is not the right place for things common to _relays_. There will be a common integrations module for that.

2024-08-01 22:01 UTC, jmank88 commented on core/internal/features/features_test.go
> +	testcommon "github.com/smartcontractkit/chainlink-common/pkg/utils/tests"
```suggestion
	"github.com/smartcontractkit/chainlink-common/pkg/utils/tests"
```

2024-08-02 00:07 UTC, reductionista commented
> This is not the right place for things common to relays. There will be a common integrations module for that.

Oh okay, I didn't realize that. If I recall, it started out as exactly that when when it was named chainlink-relay... but has gradually incorporated an assortment of other shared packages as well. 
Last I recall seeing, it still has a lot of things common to the relays which they import--is the plan to move all of that into the integrations repo at some point?

2024-08-02 00:24 UTC, jmank88 commented
> > This is not the right place for things common to relays. There will be a common integrations module for that.
> 
> Oh okay, I didn't realize that. If I recall, it started out as exactly that when when it was named chainlink-relay... but has gradually incorporated an assortment of other shared packages as well. Last I recall seeing, it still has a lot of things common to the relays which they import--is the plan to move all of that into the integrations repo at some point?

The plan was to move `chainlink/common` to `chainlink-integrations/common`. I don't know if the location changes now though :shrug:

2024-08-02 03:16 UTC, reductionista commented
> The plan was to move chainlink/common to chainlink-integrations/common. I don't know if the location changes now though 🤷

I do remember seeing some things there, come to think of it.  If all the relay modules are in that repo though, importing this common one, won't we have that issue with using replace you mentioned last week?

2024-08-02 10:43 UTC, jmank88 commented
> > The plan was to move chainlink/common to chainlink-integrations/common. I don't know if the location changes now though 🤷
> 
> I do remember seeing some things there, come to think of it. If all the relay modules are in that repo though, importing this common one, won't we have that issue with using replace you mentioned last week?

Using a relative replace is always a choice. It is never necessary.

2024-09-17 18:18 UTC, closed without merging