[TT-1421] Adds Dot Graphs to CI Upload
smartcontractkit/chainlink pull request #13946
Opened 2024-07-29 19:06 UTC by kalverra

Seth v1.1.0 introduces DOT graphs for tracing transactions. These will be uploaded as artifacts along with failed test logs to assist in debugging failing tests in CI.

2024-07-29 19:14 UTC, chainchad approved these changes, later dismissed

2024-07-30 07:29 UTC, Tofel requested changes
1. We should enable `dot` as tracing output in the default toml.
2. Could we automatically generate svg/png of the failed interaction and display it in the job summary?

2024-08-08 16:42 UTC, Tofel approved these changes

2024-08-09 11:49 UTC, lukaszcl approved these changes

2024-08-09 12:05 UTC, merged