validate ids prior to using as seed for transmission schedule
smartcontractkit/chainlink pull request #14116
Opened 2024-08-14 12:33 UTC by ettec

resolves-> https://smartcontract-it.atlassian.net/browse/KS-404

2024-08-14 12:37 UTC, cedric-cordenier approved these changes, later dismissed

2024-08-15 00:10 UTC, bolekk requested changes

2024-08-15 00:10 UTC, bolekk commented on core/capabilities/validation/validation.go
> +func ValidateWorkflowOrExecutionID(id string) error {
Do you mind keeping it in utils.go? Or alternatively moving all the validators to validation.go and their tests to validation_test.go? We are now in a messy state where some methods are here and some there... My preference is to keep stuff in utils.go as it minimizes the total amount of changes needed.

2024-08-19 14:42 UTC, ettec commented on core/capabilities/validation/validation.go
> +func ValidateWorkflowOrExecutionID(id string) error {
ah crap, yeah I should have at least moved the corresponding tests, my bad.  The utils stuff is used outside of the remote package as well now so should sit outside that, I'll tidy it up

2024-08-19 15:20 UTC, ettec commented on core/capabilities/validation/validation.go
> +func ValidateWorkflowOrExecutionID(id string) error {
I've moved the validation logic used in remote and other packages in capabilities into validation package along with the corresponding tests.  All other logic that is used only in remote package has been kept in the remote/utils.go file.

2024-08-19 20:28 UTC, bolekk approved these changes

2024-08-20 10:09 UTC, cedric-cordenier approved these changes

2024-08-20 14:43 UTC, merged