[OPCORE-863]: fix(service): start multiple feeds managers
smartcontractkit/chainlink pull request #14197
Opened 2024-08-22 07:47 UTC by graham-chainlink

## What
In order to support connection to multiple feed managers, when on start of the node, we want to  attempt to connect to list 
of registered feed managers.

## Why
In the upcoming CCIP v2, we want to be able to allow it talk to existing nodes that have been registered with CLO.

JIRA: https://smartcontract-it.atlassian.net/browse/OPCORE-863

## Note
This is not the only change to enable support for multiple feeds manager.
I have another PR soon which addresses the [hardcoding restriction](https://github.com/smartcontractkit/chainlink/blob/6ef1d6eb449ee1dc1d7d10d50990de7da55561ee/core/services/feeds/service.go#L196-L196) of 1 feeds manager.
UI will need to be tweaked to show multiple feed managers as well.

2024-08-22 12:46 UTC, eutopian requested changes
Should we make this part of the change last? Could potentially cause issues as the UI and all other parts of the code can't handle multiple managers. How does this affect how the UI picks which manager to use? Maybe we should add a feature flag to the toml config first

2024-08-22 13:19 UTC, eutopian approved these changes, later dismissed
Discussed and decided we can add the flag when [this is changed](https://github.com/smartcontractkit/chainlink/blob/e452ee1ddb520b86f827ac75cccdb0719e9f5335/core/services/feeds/service.go#L197) as the changes here alone does not actually start multiple fms

2024-08-27 07:33 UTC, ro-tex submitted a review, later dismissed

2024-08-27 13:15 UTC, MStreet3 reviewed
Is this default to false on the new flag?

2024-08-27 13:18 UTC, graham-chainlink commented
> Is this default to false on the new flag?

Yes, if no value is set in the config.toml, then the default boolean value kicks in which is false.

2024-08-27 13:20 UTC, MStreet3 commented on core/services/feeds/service.go
> -func (s *service) ListJobProposals(ctx context.Context) ([]JobProposal, error) {
Who called this method? Shouldn't the call site be replaced with the ListJobProposalsByManagerID? Unless I missed that.

2024-08-27 13:25 UTC, graham-chainlink commented on core/services/feeds/service.go
> -func (s *service) ListJobProposals(ctx context.Context) ([]JobProposal, error) {
I documented the reason in my [commit description here](https://github.com/smartcontractkit/chainlink/pull/14197/commits/5220fb97c3052fa5beb481800c5c5cc5a8ed967c)

We already have `ListJobProposalsByManagersIDs` which takes in a list of IDs, so we dont need to introduce another `ListJobProposalsByManagerID` for single ID

2024-08-29 00:51 UTC, eutopian approved these changes

2024-08-29 06:50 UTC, ro-tex approved these changes

2024-08-29 07:04 UTC, merged