[TT-1546] change the parameter of chains' Confirm() function
smartcontractkit/chainlink pull request #14388
Opened 2024-09-10 16:17 UTC by Tofel

pass `*types.Transaction` instead of `common.Hash` to chain's `Confirm()` function, so that Seth can use `Decode()` function to wait for tx to be mined and then trace it.

2024-09-10 16:32 UTC, AnieeG approved these changes

2024-09-10 17:01 UTC, AnieeG requested changes
need to fix build failure

2024-09-11 17:12 UTC, AnieeG approved these changes
LGTM

2024-09-11 17:30 UTC, kalverra approved these changes

2024-09-11 19:02 UTC, connorwstein approved these changes

2024-09-12 05:34 UTC, merged