Register polling subscription in rpc client
smartcontractkit/chainlink pull request #14534
Opened 2024-09-23 20:27 UTC by huangzhen1997

### Description
SubscribeToFinalizedHeads and SubscribeToHeads won’t abort polling subscription after Close
It could cause clients like HeadTracker to keep using subscriptions to unhealthy RPC despite MultiNode's transitioning to an unhealthy state. 
DoD: polling subscription must be registered

### Tickets:
[BCFR-946](https://smartcontract-it.atlassian.net/browse/BCFR-946

2024-09-25 14:48 UTC, dhaidashenko commented on .changeset/moody-rules-agree.md
> +- register polling subscription logic in rpc client so when node unhealthy new susbcription will be used
```suggestion
- register polling subscription to avoid subscription leaking when rpc client gets closed.
```

2024-09-25 14:48 UTC, dhaidashenko commented on core/chains/evm/client/rpc_client_test.go
> +		_, err := rpc.SubscribeNewHead(tests.Context(t), ch)
Could you check that the returned subscription is closed?

2024-09-25 14:54 UTC, huangzhen1997 commented on .changeset/moody-rules-agree.md
> +- register polling subscription logic in rpc client so when node unhealthy new susbcription will be used
I think more precisely, the sub was never added to the sub slice

2024-09-25 15:00 UTC, dhaidashenko commented on core/chains/evm/client/rpc_client_test.go
> +	_ "net/http/pprof"
debug artifact

2024-09-25 15:08 UTC, dhaidashenko commented on core/chains/evm/client/rpc_client_test.go
> +		_, ok := <-errCh
Could you use 
```
select {
<-errCh: // ok
default: fail
}
```
To return more explicit error instead of tests timeout

2024-09-27 14:00 UTC, dhaidashenko requested changes

2024-09-27 14:00 UTC, dhaidashenko commented on core/chains/evm/client/rpc_client_test.go
> +		time.Sleep(tests.TestInterval * 2)
We should always avoid `Sleep` during the tests as it leads to flaky behavior. 
Instead, we should use the channel returned by `SubscribeToHeads` to receive a new head, ensuring that it matches our expectations. After that, we can be sure that the `latest` and  `highestUserObservations` were updated.

2024-09-27 14:00 UTC, dhaidashenko commented on core/chains/evm/client/rpc_client_test.go
> +		rpc := client.NewRPCClient(lggr, *wsURL, nil, "rpc", 1, chainId, commonclient.Primary, 0, 0, commonclient.QueryTimeout, commonclient.QueryTimeout, "")
make sure that rpc is closed by the end of each test

2024-09-27 14:00 UTC, dhaidashenko commented on core/chains/evm/client/rpc_client_test.go
> +	t.Run("Closed rpc client should remove existing SubscribeNewHead subscription with WS", func(t *testing.T) {
All `Closed rpc client should remove existing...` tests have a lot in common. Could you try minimize amount of code duplication?

2024-09-27 18:40 UTC, huangzhen1997 commented on core/chains/evm/client/rpc_client.go
> +	subsSliceMu sync.RWMutex // protects subscription slice
a deadlock was caught by my new unit tests, and this fixes it.

2024-09-27 19:01 UTC, amit-momin approved these changes

2024-09-30 12:49 UTC, dhaidashenko approved these changes
Nice work!

2024-09-30 15:41 UTC, merged