Mercury transmitter can use different codecs for native & link price reports
smartcontractkit/chainlink pull request #14631
Opened 2024-10-02 08:50 UTC by martin-cll

We are seeing the following error with a new v4 Mercury feed in staging testnet: `failed to observe LINK price: failed to decode report: abi: improperly encoded uint32 value\nfailed to observe native price: failed to decode report: abi: improperly encoded uint32 value`.

I believe this is caused by a v4 feed that uses a v3 native/link feedId:
* The native/link price is returned by the `fetcher.LatestPrice` here: https://github.com/smartcontractkit/chainlink/blob/develop/core/services/relay/evm/mercury/v4/data_source.go#L110-L149.
* I think, but I'm not 100% sure, that the fetcher is in fact a MercuryTransmitter: https://github.com/smartcontractkit/chainlink/blob/develop/core/services/relay/evm/mercury/transmitter.go#L497.
* The issue is that the mercury transmitter uses its internal codec to decode the link/native feed's reports so if the feed versions are different then it will get a decoding error which is what we are seeing in the logs.

The fix in this PR is to pass down a new `BenchmarkPriceDecoder` method that switches on the feedId to select the appropriate codec before decoding it for its benchmark price.

2024-10-02 08:53 UTC, martin-cll commented on .changeset/cuddly-colts-speak.md
> +Fix for Mercury transmitter decoding reports of a different codec version
```suggestion
Fix for Mercury transmitter decoding reports of a different codec version #internal
```

2024-10-02 12:28 UTC, ro-tex submitted a review, later dismissed

2024-10-02 13:01 UTC, samsondav requested changes
This is implemented incorrectly

You’re supposed to create a different codec and pass that in

2024-10-03 13:05 UTC, samsondav approved these changes

2024-10-03 13:16 UTC, ad0ll approved these changes

2024-10-03 16:16 UTC, patrickhuie19 approved these changes

2024-10-03 16:38 UTC, merged