feat: add getNextDonId and batch getNodes getter
smartcontractkit/chainlink pull request #14696
Opened 2024-10-09 12:49 UTC by 0xsuryansh

### Requires

### Resolves

2024-10-11 17:23 UTC, justinkaseman requested changes

2024-10-11 17:23 UTC, justinkaseman commented on contracts/src/v0.8/keystone/CapabilitiesRegistry.sol
>    function typeAndVersion() external pure override returns (string memory) {
Let's do something with the version here. Otherwise it is more difficult to track changes on deployed contracts.

2024-10-18 06:26 UTC, DeividasK submitted a review, later dismissed

2024-10-18 07:25 UTC, makramkd submitted a review, later dismissed

2024-10-18 10:16 UTC, RensR commented on contracts/src/v0.8/keystone/interfaces/INodeInfoProvider.sol
> +pragma solidity 0.8.24;
please set to `^0.8.4`

2024-10-21 06:02 UTC, DeividasK approved these changes

2024-10-21 06:20 UTC, makramkd approved these changes

2024-10-21 07:54 UTC, RensR approved these changes

2024-10-21 15:31 UTC, justinkaseman approved these changes

2024-10-21 15:40 UTC, patrickhuie19 approved these changes

2024-10-21 15:55 UTC, merged