Handle Hex String in Utils.ToDecimal
smartcontractkit/chainlink pull request #14827
Opened 2024-10-17 13:17 UTC by cawthorne

The EA Telemetry currently fails for EAs where their result is a hex string:
https://smartcontract-it.atlassian.net/browse/DF-20580

2024-10-17 13:41 UTC, mxiao-cll submitted a review, later dismissed

2024-10-17 15:50 UTC, george-dorin requested changes
It seems that the behavior of not being able to convert hex to decimal is expected by Median and Mercury. As an alternative, perhaps we could add the hex conversion logic specifically for telemetry parsing?

2024-10-18 10:06 UTC, george-dorin submitted a review, later dismissed

2024-10-18 10:16 UTC, cawthorne commented
@george-dorin I managed to get all test passing with the original approach with changing ToDecimal:
https://github.com/smartcontractkit/chainlink/pull/14841

My original patch had a bug in.

I was unsure if your comment `It seems that the behavior of not being able to convert hex to decimal is expected by Median and Mercury`, was based on the tests failing, or if that is actually the case.

We can choose which approach we want, and close the PR we don't merge in.

2024-10-18 10:24 UTC, george-dorin commented
@cawthorne I was basing this on the tests, and it seems to me that `ToDecimal` should know how to interpret hex. However, I'm not entirely sure if other products are expecting the conversion to fail

2024-10-18 14:05 UTC, cawthorne commented
@george-dorin I am fine with easier, perhaps it would make sense to just do the telemetry at first, and then the more general solution could come later if there's a need.

2024-10-23 12:53 UTC, pavel-raykov commented on core/services/ocrcommon/telemetry.go
Could you please update the comment of this function getJsonParsedValue?

2024-10-23 13:09 UTC, cawthorne commented on core/services/ocrcommon/telemetry.go
Thanks, I added some extra comments about the issue. I can remove some detail from them if you think it is too much.

2024-10-23 13:12 UTC, pavel-raykov commented on core/services/ocrcommon/telemetry.go
It is fine. Thanks.

2024-10-23 13:12 UTC, pavel-raykov submitted a review, later dismissed

2024-10-23 13:12 UTC, cedric-cordenier submitted a review, later dismissed

2024-10-23 13:13 UTC, george-dorin submitted a review, later dismissed

2024-10-23 15:08 UTC, pavel-raykov approved these changes

2024-10-23 15:20 UTC, george-dorin approved these changes

2024-10-24 07:47 UTC, merged