bumping common
smartcontractkit/chainlink pull request #14902
Opened 2024-10-22 20:20 UTC by patrickhuie19

Supports https://github.com/smartcontractkit/chainlink-common/pull/876 in common

2024-10-23 00:38 UTC, vyzaldysanchez requested changes

2024-10-23 00:38 UTC, vyzaldysanchez commented on core/monitoring/monitoring.go
This file will not exist in core anymore, the labeler was moved to common. Would you please update the labelers in common to reflect this?

2024-10-23 01:16 UTC, patrickhuie19 commented on core/monitoring/monitoring.go
good catch, thanks

2024-10-25 02:24 UTC, patrickhuie19 commented
no longer needed; https://github.com/smartcontractkit/chainlink/pull/14867/ merged

2024-10-25 02:24 UTC, closed without merging