Keystone e2e test
smartcontractkit/chainlink pull request #15182
Opened 2024-11-11 10:57 UTC by DeividasK

**Follow-ups**

- Use CL image created during the `build` step instead of re-creating it.
- Pull streams capability from a published docker image (instead of adding the binary to the repo here)

2024-11-12 14:40 UTC, iljapavlovs commented on e2e/capabilities/workflow_test.go
> +				bc.Nodes[0].HostWSUrl,
should be using Docker URL instead since communication is performed inside Docker network

2024-11-12 14:40 UTC, iljapavlovs commented on e2e/capabilities/workflow_test.go
> +				bc.Nodes[0].HostHTTPUrl,
should be using Docker URL instead since communication is performed inside Docker network

2024-11-12 14:41 UTC, iljapavlovs commented on e2e/capabilities/workflow_test.go
> +				bc.Nodes[0].HostWSUrl,
should be using Docker URL instead since communication is performed inside Docker network

2024-11-12 14:41 UTC, iljapavlovs commented on e2e/capabilities/workflow_test.go
> +				bc.Nodes[0].HostHTTPUrl,
should be using Docker URL instead since communication is performed inside Docker network

2024-11-12 14:41 UTC, iljapavlovs commented on e2e/capabilities/workflow_test.go
> +					strings.TrimPrefix(nodeset.CLNodes[0].Node.HostP2PURL, "http://"),
should be using Docker URL instead since communication is performed inside Docker network

2024-11-27 14:35 UTC, DeividasK commented on .github/workflows/e2e.yml
> +        run: go test -v -timeout 30m -run TestWorkflow
How do we make it so that all e2e tests run?

2024-11-27 14:37 UTC, DeividasK commented on e2e/tests/workflow_test.go
> +}
Returning this bundle should be part of the Node API (instead of individual API calls)

2024-11-27 17:48 UTC, jmank88 commented on e2e/go.mod
Why create a new module, as opposed to extending the `integration-tests/` module, which is de-facto end-to-end tests?

2024-11-27 17:50 UTC, jmank88 commented on e2e/go.mod
Actually, based on the dependencies, why not put this new module inside of the CTF repo? Because it only depends on libocr and CTF.

2024-11-27 18:26 UTC, DeividasK commented on e2e/go.mod
@skudasov

2024-11-27 20:04 UTC, skudasov commented on e2e/go.mod
We've discussed with @jmank88  that we should move this test to a separate end-to-end repository. CTF is a public repository, so we need an internal repo that every team can use.

2024-11-28 11:39 UTC, DeividasK commented on e2e/go.mod
> Actually, based on the dependencies, why not put this new module inside of the CTF repo? Because it only depends on libocr and CTF.

We are testing the latest core image build to be compatible with the rest of the system. The test depends on the CL docker image, and we want to run e2e tests every time the CL image changes.

2024-12-02 13:46 UTC, jmank88 commented on e2e/go.mod
@skudasov Do you mean move to a separate repo now, instead of this PR? If not, then why have these in a separate module, rather than putting them in the `integration-tests/` module, which is the defacto end-to-end test definition module that IIUC behaves exacly as @DeividasK is describing.

2024-12-02 13:47 UTC, jmank88 commented on e2e/go.mod
Oh nvm, I see that the structure was refactored.

2024-12-04 08:44 UTC, jmank88 requested changes

2024-12-04 08:44 UTC, jmank88 commented on integration-tests/capabilities/streams-linux-amd64
Please don't commit binaries

2024-12-20 03:53 UTC, krehermann commented on integration-tests/capabilities/components/evmcontracts/capabilities_registry/capabilities_registry.go
> +func Deploy(sc *seth.Client) (*CapabilitiesRegistryInstance, error) {
can we not reuse, extend and unify on the work in deployment/keystone?

ccip is doing something similiar -- all deployment logic is unified and they have a `devenv` for integration tests

2025-02-26 00:16 UTC, closed without merging