Add donID to mercury EA telemetry
smartcontractkit/chainlink pull request #15197
Opened 2024-11-12 08:37 UTC by mjk90

[MERC-6605](https://smartcontract-it.atlassian.net/browse/MERC-6605)

Get donId from config & send in Mercury Enhanced EA Telemetry

2024-11-12 09:57 UTC, ro-tex approved these changes, later dismissed

2024-11-12 09:57 UTC, brunotm submitted a review, later dismissed

2024-11-12 13:45 UTC, samsondav requested changes

2024-11-12 13:45 UTC, samsondav commented on core/services/llo/delegate.go
> +		t = NewTelemeterService(lggr, cfg.EAMonitoringEndpoint, cfg.DonID)
Nice, can we add it to the starting log on line 114 as well?

2024-11-12 13:45 UTC, samsondav commented on core/services/synchronization/telem/telem_enhanced_ea_mercury.proto
> +  uint32 don_id=36;
If we're going to make modifications, may I suggest also adding `string stream_id` and then we can put the feed ID in the `feed` field?

2024-11-12 13:45 UTC, samsondav commented on core/services/llo/delegate.go
> +		t = NewTelemeterService(lggr, cfg.EAMonitoringEndpoint, cfg.DonID)
Also to the `logger.With` statement, would be nice (line 77)

2024-11-12 14:57 UTC, samsondav submitted a review, later dismissed

2024-11-13 08:54 UTC, msuchacz-cll approved these changes

2024-11-13 09:17 UTC, martin-cll approved these changes

2024-11-13 14:50 UTC, samsondav approved these changes

2024-11-13 15:35 UTC, merged