Initialization for Crib
smartcontractkit/chainlink pull request #15501
Opened 2024-12-04 12:54 UTC by 0xAustinWang

https://smartcontract-it.atlassian.net/browse/CCIP-4107

2024-12-11 11:00 UTC, scheibinger approved these changes, later dismissed
Tested in crib staging env and that fully worked 🎉

2024-12-11 15:18 UTC, b-gopalswami approved these changes, later dismissed

2024-12-11 15:18 UTC, b-gopalswami commented on deployment/environment/devenv/don.go
> +		// retry twice with 5 seconds interval to create JobDistributorChainConfig
nit: update comment per retry interval

2024-12-11 20:32 UTC, AnieeG commented on deployment/ccip/changeset/cs_home_chain.go
> +func DeployCapReg(
These deploy funcs are intentionally made unexported. If you are using this please use the changeset corresponding to it. These should not be exported

2024-12-11 20:32 UTC, AnieeG commented on deployment/environment/devenv/don.go
> +		return resp.FeedsManagers.Results[0].FeedsManagerParts.GetId(), nil
I think this should be updated to check if the csakey matches with the JD, it should not just return the first one in the result

2024-12-11 20:36 UTC, AnieeG requested changes
Requesting change for the update of JD

2024-12-12 14:41 UTC, AnieeG approved these changes

2024-12-12 14:53 UTC, b-gopalswami approved these changes

2024-12-12 15:54 UTC, 0xnogo approved these changes

2024-12-12 16:27 UTC, makramkd approved these changes

2024-12-13 03:19 UTC, merged