Improvements
smartcontractkit/chainlink pull request #15695
Opened 2024-12-14 13:39 UTC by dimriou

2024-12-15 14:35 UTC, pavel-raykov commented on core/services/chainlink/config_test.go
> +			- TxmV2.TxmV2.BlockTime: missing: must be set if txmv2 feature is enabled
extra TxmV2?

2024-12-15 15:17 UTC, pavel-raykov requested changes

2024-12-15 15:17 UTC, pavel-raykov commented on core/services/chainlink/config_test.go
> +			- TxmV2.TxmV2.BlockTime: missing: must be set if txmv2 feature is enabled
extra TxmV2?

2024-12-15 15:17 UTC, pavel-raykov commented on core/chains/evm/txm/stuck_tx_detector.go
> +	if tx.LastBroadcastAt != nil && min(time.Since(*tx.LastBroadcastAt), time.Since(s.lastPurgeMap[tx.FromAddress])) > threshold {
Can s.lastPurgeMap[tx.FromAddress] also be nil?

2024-12-15 15:17 UTC, pavel-raykov commented on core/chains/evm/txm/storage/inmemory_store_manager.go
> -			return fmt.Errorf("address %v already exists in store manager", address)
why is it fine to continue updating m.InMemoryStoreMap[address]  in case exists is true? (Before this PR, we would have returned)

2024-12-15 15:17 UTC, pavel-raykov commented on core/chains/evm/config/toml/config.go
> +		case chaintype.ChainDualBroadcast:
Could you please update the PR description? Right now it just says "improvements", whereas, at least it takes care of the ChainDualBroadcast chain type. 

Please, also specify what is the old vs new behavior after this PR is merged.

2024-12-16 17:39 UTC, george-dorin approved these changes

2024-12-17 09:18 UTC, pavel-raykov approved these changes

2024-12-20 11:08 UTC, closed without merging