Feature/ks 460/heartbeat
smartcontractkit/chainlink pull request #15700
Opened 2024-12-16 05:37 UTC by patrickhuie19

### Requires

### Supports

2025-01-10 16:46 UTC, pkcll commented on core/services/chainlink/config_telemetry.go
> +		"service.sha":          static.Sha,
👍

2025-01-10 16:54 UTC, vyzaldysanchez requested changes

2025-01-10 16:54 UTC, vyzaldysanchez commented on core/services/chainlink/application.go
> +const ApplicationHeartbeatSeconds = 1
Shouldn't this already by `1 * time.Second`? At least based on the naming?

2025-01-10 16:54 UTC, vyzaldysanchez commented on core/services/chainlink/application.go
> +		lggr: lggr,
We should name this logger using `lggr.Named("ApplicationHeartbeat or NodeHeartbeat")` maybe?

2025-01-10 16:54 UTC, vyzaldysanchez commented on core/services/chainlink/application.go
> +func (h *ApplicationHeartbeat) start(_ context.Context) error {
We don't care about this context?

2025-01-10 20:23 UTC, patrickhuie19 commented on core/services/chainlink/application.go
> +const ApplicationHeartbeatSeconds = 1
durations can not be initialized as a `const`, which I'd like to preserve. I'm open to other names. what would you suggest?

2025-01-10 20:34 UTC, jmank88 commented on core/services/chainlink/application.go
> +const ApplicationHeartbeatSeconds = 1
What do you mean? This is valid:
```suggestion
const ApplicationHeartbeat = time.Second
```
It is no longer an _untyped_ `const`, but does that matter?

2025-01-10 20:36 UTC, patrickhuie19 commented on core/services/chainlink/application.go
> +		lggr: lggr,
The engine removes the need for that pattern: by specifying the `Name: "NodeHeartbeat"` in line 213 the engine will do that for us under the hood

2025-01-10 20:38 UTC, patrickhuie19 commented on core/services/chainlink/application.go
> +func (h *ApplicationHeartbeat) start(_ context.Context) error {
Correct, we don't need. None of the sync resource initialization relies on it, and the tick function is supposed to use the ctx that is passed into the engine so it can continue async relative to the `start` call. If it used the `start` context, the tick function would stop running after the application start logic finishes.

2025-01-10 20:39 UTC, jmank88 commented on core/services/chainlink/application.go
> +		lggr: lggr,
but then you should either drop this field to use the engine logger directly, or init this field from the engine.

2025-01-10 20:42 UTC, jmank88 commented on core/services/chainlink/application.go
> +}
A method might be simpler here:
```suggestion
	h.eng.GoTick(timeutil.NewTicker(h.getBeat), beatFn)
	return nil
}

func (h *ApplicationHeartbeat) getBeat() time.Duration { return h.beat }
```

2025-01-10 20:44 UTC, jmank88 commented on core/services/chainlink/application.go
> +	beatFn := func(engCtx context.Context) {
IMHO alternate names for context confuse things and lead to accidental misuse.
```suggestion
	beatFn := func(ctx context.Context) {
```
If there are multiple contexts in scope leading to a linter problem, then it is typically cleaner to separate the nested scopes. In this case, a method could work. Although I don't see a nesting problem.

2025-01-10 20:48 UTC, vyzaldysanchez commented on core/services/chainlink/application.go
> +		lggr: lggr,
I agree with @jmank88 here.

2025-01-10 21:00 UTC, patrickhuie19 commented on core/services/chainlink/application.go
> +const ApplicationHeartbeatSeconds = 1
hmm. i was fairly certain the last time I tried to do something similar in the workflow engine I was unable to use a const to capture something like (5 * time.Second).

2025-01-10 21:02 UTC, patrickhuie19 commented on core/services/chainlink/application.go
> +		lggr: lggr,
Thanks both; agreed will use the eng logger

2025-01-10 21:12 UTC, patrickhuie19 commented on core/services/chainlink/application.go
> +	beatFn := func(engCtx context.Context) {
>IMHO alternate names for context confuse things and lead to accidental misuse.

Oh, huh. I liked that it was clearer for me. Even after putting this down for a while I immediately knew when i picked it back up what deadline considerations were in scope for the method. 

I do see that it could mess with tooling. It also is clearer in this case because the context passed to `start` is unused.

2025-01-13 18:52 UTC, vyzaldysanchez submitted a review, later dismissed

2025-01-13 20:38 UTC, jmank88 commented on core/services/chainlink/application.go
> +		Name:  "NodeHeartbeat",
Would it still be clear if this type/service was called just `HeartBeat`?
```suggestion
func NewHeartbeat(lggr logger.Logger) Heartbeat {
	h := Heartbeat{
		beat: HeartbeatPeriod,
	}
	h.Service, h.eng = commonservices.Config{
		Name:  "Heartbeat",
```

2025-01-13 20:41 UTC, patrickhuie19 commented on core/services/chainlink/application.go
> +		Name:  "NodeHeartbeat",
Wanted to keep it open to next migrating this to a more generic Heartbeat type in common: https://github.com/smartcontractkit/chainlink-common/pull/976/files

2025-01-13 20:53 UTC, jmank88 commented on core/services/chainlink/application.go
> +		Name:  "NodeHeartbeat",
I think it would be OK to reuse the name, if the intent is not to use two at the same time :shrug:

2025-01-14 15:33 UTC, patrickhuie19 commented on core/services/chainlink/application.go
> +		Name:  "NodeHeartbeat",
https://github.com/smartcontractkit/chainlink/pull/15700/commits/74261f48bad52fad3e9578bac8328f8bf0c64498

2025-01-14 15:50 UTC, jmank88 commented on core/services/chainlink/application.go
> +	}
Is it important to check these on start, and necessary to fail if they are not available? Or could we defer, and recall these each tick, in order to allow startup and recovery later if necessary?

If it does make sense to move them inside the tick func, maybe consider making it a separate method too.

2025-01-14 16:54 UTC, patrickhuie19 commented on core/services/chainlink/application.go
> +	}
These specific resources, no. I don't expect them to fail, and their production implementations don't return errors:
```
func (m *meter) Int64Gauge(name string, options ...metric.Int64GaugeOption) (metric.Int64Gauge, error) {
	m.mtx.Lock()
	defer m.mtx.Unlock()

	if m.delegate != nil {
		return m.delegate.Int64Gauge(name, options...)
	}

	cfg := metric.NewInt64GaugeConfig(options...)
	id := instID{
		name:        name,
		kind:        reflect.TypeOf((*siGauge)(nil)),
		description: cfg.Description(),
		unit:        cfg.Unit(),
	}
	if f, ok := m.instruments[id]; ok {
		return f.(metric.Int64Gauge), nil
	}
	i := &siGauge{name: name, opts: options}
	m.instruments[id] = i
	return i, nil
}
```

I'd like to avoid putting resource init in the tick. I do think you've raised a good point re: recovery. I think the generic heartbeat is the better place to handle that. Since the init func is passed in as a consumer defined method there anyways, the generic heartbeat could handle a failure by storing that the resource init never completed successfully and then the next tick could try the resource init. 

Consumers would have to be aware of this and ensure that the resource inits are idempotent, though. Or the generic heartbeat could handle this by having a user defined `onClose` functionality to erase un-wanted side-effects before the next tick invocation.

2025-01-14 17:09 UTC, vyzaldysanchez submitted a review, later dismissed

2025-01-14 17:26 UTC, jmank88 commented on core/services/chainlink/application.go
> +}
You can omit this if there is nothing to do
```suggestion
```

2025-01-15 18:10 UTC, jmank88 approved these changes

2025-01-15 18:21 UTC, vyzaldysanchez approved these changes

2025-01-15 19:05 UTC, krehermann approved these changes

2025-01-15 19:08 UTC, merged