CCIP-4723 Feat/burn to zero address pool
smartcontractkit/chainlink pull request #15804
Opened 2024-12-23 22:16 UTC by jhweintraub

1. Add two new pool types: `SiloedLockReleaseTokenPool` and `BurnToAddressTokenPool`
3. Fix `TransferLiquidity` Bug in `HybridUSDCTokenPool` that prevents function from being called sequentially

2025-01-07 13:35 UTC, RensR requested changes

2025-01-07 13:35 UTC, RensR commented on contracts/src/v0.8/ccip/pools/BurnToAddressMintTokenPool.sol
> +  /// @notice Tokens are burned by sending to an address which is expected to have no corresponding private key,
Any address can be chosen, which makes the claim `which is expected to have no corresponding private key` incorrect

2025-01-07 13:35 UTC, RensR commented on contracts/src/v0.8/ccip/pools/BurnToAddressMintTokenPool.sol
> +/// @dev This contract is a variant of BurnMintTokenPool that uses `burn(amount)`.
stale comment

2025-01-07 13:35 UTC, RensR commented on contracts/src/v0.8/ccip/pools/BurnToAddressMintTokenPool.sol
> +  address public immutable i_burnAddress;
Could use a comment

2025-01-07 13:35 UTC, RensR commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +  string public constant override typeAndVersion = "SiloedLockReleaseTokenPool 1.5.10-dev";
typo 1.5.10

2025-01-07 13:35 UTC, RensR commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +  mapping(uint64 chainSelector => uint256 lockedBalance) internal s_lockedTokensByChainSelector;
inconsistent naming, this is also the remote

2025-01-07 13:35 UTC, RensR commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +  mapping(uint64 remoteChainSelector => bool shouldSiloFunds) internal s_siloedChainSelectors;
These are three mappings all with the same key. This is probably not the most gas efficient solution

2025-01-07 13:35 UTC, RensR commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +      s_lockedTokensByChainSelector[releaseOrMintIn.remoteChainSelector] -= localAmount;
probably good to mention this underflows if there isn't enough to release and with that it protects the other lanes? 

On that note: how does this protect the siloed funds from being given to a non-soloed lane?

2025-01-07 13:35 UTC, RensR commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +  function getLockedTokensByChain(
Inconsistent naming tokens/funds

2025-01-07 13:35 UTC, RensR commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +  function updateChainSelectorMechanisms(uint64[] calldata removes, uint64[] calldata adds) external onlyOwner {
Name does not tell me what this function does

2025-01-07 13:35 UTC, RensR commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +    if (s_siloedChainSelectors[remoteChainSelector]) return s_rebalancerByChain[remoteChainSelector];
Why do rebalancers only work for siloed chains? That breaks the current operations we do for weth

2025-01-07 15:22 UTC, jhweintraub commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +    if (s_siloedChainSelectors[remoteChainSelector]) return s_rebalancerByChain[remoteChainSelector];
The idea was to make specific siloed chains have specific rebalancers so they can provide their own liquidity. This was a hard requirement for a current client. For non-siloed chains CLL would remain the rebalancer which operates like it does now for WETH

2025-01-07 15:25 UTC, jhweintraub commented on contracts/src/v0.8/ccip/pools/BurnToAddressMintTokenPool.sol
> +  /// @notice Tokens are burned by sending to an address which is expected to have no corresponding private key,
There's no way within the EVM to verify that that is true . It is expected that it will be `address(0)` but future clients may desire something else esp. if for an L2 address(0) is a precompile.

`Therefore the zero address is a valid input, and no check for non-zero address is performed.`

2025-01-07 15:27 UTC, jhweintraub commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +  string public constant override typeAndVersion = "SiloedLockReleaseTokenPool 1.5.10-dev";
Should be 1.6.0?

2025-01-07 15:27 UTC, jhweintraub commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +  mapping(uint64 chainSelector => uint256 lockedBalance) internal s_lockedTokensByChainSelector;
This is not remote. This will be deployed on the home-chain to replace the WETH lock-release token pool. While it could be deployed on a remote chain that is not its current intended functionality.

2025-01-07 15:33 UTC, jhweintraub commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +  function getLockedTokensByChain(
Will update to `getSiloedTokensByChain()`

2025-01-07 15:34 UTC, jhweintraub commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +      s_lockedTokensByChainSelector[releaseOrMintIn.remoteChainSelector] -= localAmount;
Good point. There should probably be an additional internal state variable for tracking the joint non-siloed funds.

2025-01-15 13:26 UTC, RensR commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +  mapping(uint64 chainSelector => uint256 lockedBalance) internal s_lockedTokensByChainSelector;
It's the chain selector for a remote chain no?

2025-01-15 13:26 UTC, RensR commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +  string public constant override typeAndVersion = "SiloedLockReleaseTokenPool 1.5.10-dev";
Yes 1.6.0

2025-01-15 14:16 UTC, RensR reviewed
didn't look at the tests yet, will do after these comments are addressed

2025-01-15 14:16 UTC, RensR commented on contracts/src/v0.8/ccip/pools/BurnToAddressMintTokenPool.sol
> +    s_lockedTokens -= releaseOrMintIn.amount;
Let's add a proper error instead of underflow reverts. A good way to ensure you always have proper error handling is to never allow a test to assert a revert without being explicit. Since we always test every error case, that means when you encounter that error case, to properly test it it has to have a custom error

2025-01-15 14:16 UTC, RensR commented on contracts/src/v0.8/ccip/pools/BurnToAddressMintTokenPool.sol
> +    return s_lockedTokens;
So we ever need to set locked tokens outside of the constructor? I could see a world where you deploy this well before you shut off the existing bridge and you don't know the total locked on deploy time. Maybe worth a setter and potentially removing it from the constructor?

2025-01-15 14:16 UTC, RensR commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +
nit: rm newline

2025-01-15 14:16 UTC, RensR commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +  event LiquidityRemoved(uint64 remoteChainSelector, address indexed provider, uint256 indexed amount);
why index the amounts?

2025-01-15 14:16 UTC, RensR commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +  event SiloedChainRebalancerSet(uint64 indexed remoteChainSelector, address oldRebalancer, address newRebalancer);
nit: SiloRebalancerSet?

2025-01-15 14:16 UTC, RensR commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +  struct ChainSiloConfig {
A silo can only contain a single chain, correct? Do we foresee any scenario where we need multiple chains in a silo so they share funds? I don't think so but let's think about it

2025-01-15 14:16 UTC, RensR commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +  string public constant override typeAndVersion = "SiloedLockReleaseTokenPool 1.6.0";
always suffix unaudited code with `-dev`

2025-01-15 14:16 UTC, RensR commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +  address internal s_unsiloedChainRebalancer;
nit; rm `chain` as it's not a single chain, its the rebalancer for anything unsiloed. Is unsiloed a word?

2025-01-15 14:16 UTC, RensR commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +    bool isSiloed; // ────────────╯ Whether funds should be isolated from all other chains or shared amongst all non-siloed chains.
nit: shorter ───

2025-01-15 14:16 UTC, RensR commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +    address unsiloedChainRebalancer
Do we need this in the constructor? I'd say match the LockRelease pool which also doesn't have it

2025-01-15 14:16 UTC, RensR commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +      s_siloedChainConfigs[releaseOrMintIn.remoteChainSelector].siloedBalance -= localAmount;
same as the other, let's check instead of doing a silent revert when there's no funds

2025-01-15 14:16 UTC, RensR commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +  function chainFundsAreSiloed(
nit: rename to isSiloed?

2025-01-15 14:16 UTC, RensR commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +  function getSiloedTokensByChain(
nit: rename `getAvailableTokens`? I don't think we have to have the word silo in every call. That name then also covers the non-siloed chains

2025-01-15 14:16 UTC, RensR commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +  function getliquidityForUnsiloedChains() public view returns (uint256) {
Do we need this if we also have the function above?

2025-01-15 14:16 UTC, RensR commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +  function updateSiloDesignationForChainSelectors(
nit: rm the `ForChainSelectors` part of the name

2025-01-15 14:16 UTC, RensR commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +      /// @notice Removing the entire configuration will also delete the rebalancer. If the chain ever becomes siloed
natspec isn't allowed here, just a `//` is fine. Please also address in other parts of the PR. `///` or `/// @notice` isn't allowed everywhere, only above definitions (func/struct/var/const/..)

2025-01-15 14:16 UTC, RensR commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +      /// @notice Adding a chain to siloing will not set the rebalancer
stale comment

2025-01-15 14:16 UTC, RensR commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +      s_siloedChainConfigs[adds[i].remoteChainSelector].rebalancer = adds[i].rebalancer;
I'd prefer a single assignment of the entire struct instead of two assignments of parts of the struct

2025-01-15 14:16 UTC, RensR commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +      emit ChainSiloed(adds[i].remoteChainSelector);
let's add the rebalancer as well

2025-01-15 14:16 UTC, RensR commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +      // Emit a siloing event to indicate that the chain is now siloed, but that the amount of liquidity
Not sure we need this comment, and not sure the comment is true. The event does not contain any liquidity information

2025-01-15 14:16 UTC, RensR commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +    if (remoteConfig.isSiloed) return remoteConfig.rebalancer;
I know this is perfectly legal Solidity but let's add `{ }` and remove the else. No else needed if the `if` returns

2025-01-15 14:16 UTC, RensR commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +  function setSiloedChainRebalancer(uint64 remoteChainSelector, address newRebalancer) external onlyOwner {
How do you feel about merging this and setUnsiloedChainRebalancer and just having `0` indicate the not-siloed group?

2025-01-15 14:16 UTC, RensR commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +  /// @param newRebalancer the address allowed to add liquidity for the given siloed chain.
Probably good to add a `@dev` to say that 0 is a valid value and no 0 check is required?

2025-01-15 14:16 UTC, RensR commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +  /// @dev Since the remoteChainSelector 0 should never be applied to a real chain, it is used to designate unsiloed chains.
> remoteChainSelector 0 should never be applied to a real chain

We can even make sure that 0 is not treated as valid in the `updateSiloDesignationForChainSelectors` function to ensure it's correct

2025-01-15 14:16 UTC, RensR commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +    ChainSiloConfig storage remoteConfig = s_siloedChainConfigs[remoteChainSelector];
nit: siloConfig?

2025-01-15 14:16 UTC, RensR commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +  function withdrawLiquidity(
Maybe just merge and have 0 be a value the user submits and we don't have a separate func?

2025-01-15 14:16 UTC, RensR commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +    if (s_siloedChainConfigs[remoteChainSelector].isSiloed) {
Let's have proper error handling here as well

2025-01-15 14:16 UTC, RensR commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +  function _withdrawLiquidity(uint64 remoteChainSelector, uint256 amount) internal {
Should we allow sending to not the msg.sender but a supplied address?

2025-01-15 14:50 UTC, jhweintraub commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +    if (s_siloedChainConfigs[remoteChainSelector].isSiloed) {
The error handling is that it will underflow and revert, do you need to do an explicit check for the underflow anyways? That only adds gas.

2025-01-15 14:56 UTC, jhweintraub commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +  event SiloedChainRebalancerSet(uint64 indexed remoteChainSelector, address oldRebalancer, address newRebalancer);
I think it's useful to have one event for Siloed Chains and one for unSiloed chains to avoid confusion.

2025-01-15 14:58 UTC, jhweintraub commented on contracts/src/v0.8/ccip/pools/BurnToAddressMintTokenPool.sol
> +    return s_lockedTokens;
Yes but that also potentially adds a rug vector for the pool owner to prevent users from being able to move funds out of the chain by setting the locked tokens to zero. By setting in the constructor it at least ensures that all incoming funds can be transferred out at some point.

2025-01-15 14:58 UTC, jhweintraub commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +  struct ChainSiloConfig {
At this moment in time no that is not a requirement requested by the client. Good idea, let's revisit later if necessary.

2025-01-15 15:05 UTC, jhweintraub commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +  function chainFundsAreSiloed(
Gramatically with the plural form of "funds" it would be "are" but we can change it to "isSiloed" instead.

2025-01-15 15:07 UTC, jhweintraub commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +  function getliquidityForUnsiloedChains() public view returns (uint256) {
Not explicitly necessary but I think it can be useful to have anyways just so you don't have to explicitly call availableFunds with a remoteChainSelector of 0 or something.

2025-01-15 15:09 UTC, jhweintraub commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +      s_siloedChainConfigs[adds[i].remoteChainSelector].rebalancer = adds[i].rebalancer;
The struct doesn't include the amount available since we don't want that to be able to be set manually.

2025-01-15 15:12 UTC, jhweintraub commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +  function setSiloedChainRebalancer(uint64 remoteChainSelector, address newRebalancer) external onlyOwner {
I thought about that. I think that the best way to handle it is to keep it in its own function and just rename the other function `setRebalancer` so that it uses the same function selector as LockReleaseTokenPool, to ease the burden on the tooling team.

2025-01-15 15:14 UTC, jhweintraub commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +  /// @dev Since the remoteChainSelector 0 should never be applied to a real chain, it is used to designate unsiloed chains.
Stale Comment. Removing.

2025-01-15 15:15 UTC, jhweintraub commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +  function withdrawLiquidity(
It was requested that this remain for the finance team to not have to do more tooling work by using the existing function selectors.

2025-01-15 15:19 UTC, jhweintraub commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +  function _withdrawLiquidity(uint64 remoteChainSelector, uint256 amount) internal {
Perhaps but the goal is to maintain parity with the LockReleaseTokenPool function's currently in use.

2025-01-16 16:22 UTC, RensR commented on contracts/src/v0.8/ccip/pools/BurnToAddressMintTokenPool.sol
> +  uint256 internal s_mintedTokens;
maybe `outstandingTokens` better conveys what it is? They're effectively the tokens in circulation on this chain, maybe add that to the comment

2025-01-16 16:22 UTC, RensR commented on contracts/src/v0.8/ccip/pools/BurnToAddressMintTokenPool.sol
> +      revert InsufficientMintedTokens();
Insufficient outstanding supply or something?

2025-01-16 16:22 UTC, RensR commented on contracts/src/v0.8/ccip/pools/BurnToAddressMintTokenPool.sol
> +    s_mintedTokens += releaseOrMintIn.amount;
Let's add comments to the += here and the -= below because this took me some effort to wrap my head around. Maybe changing the name helps but something along the lines of 
// minting tokens on this chain increased the outstanding supply of tokens

and 

// when tokens are sent to another chain, it decreases the local token supply

2025-01-16 16:22 UTC, RensR commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +    // it must be ensured that the remoteChainSelector can be trusted.
not sure how we can trust a chainselector? You mean "don't mess up the config"? I think that kinda holds for all contacts :p

2025-01-16 16:22 UTC, RensR commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +      s_chainConfigs[adds[i].remoteChainSelector] = newConfig;
let's disallow chainselector 0

2025-01-16 16:22 UTC, RensR commented on contracts/src/v0.8/ccip/test/pools/SiloedLockReleaseTokenPool/SiloedLockReleaseTokenPool.lockOrBurn.t.sol
> +    amount = 10e18;
When every test uses a set amount you can probably just set a const in SiloedLockReleaseTokenPoolSetup

2025-01-16 16:22 UTC, RensR commented on contracts/src/v0.8/ccip/test/pools/SiloedLockReleaseTokenPool/SiloedLockReleaseTokenPool.releaseOrMint.t.sol
> +import {IERC20} from "../../../../vendor/openzeppelin-solidity/v4.8.3/contracts/interfaces/IERC20.sol";
nit: vendor at the bottom

2025-01-16 16:28 UTC, jhweintraub commented on contracts/src/v0.8/ccip/pools/SiloedLockReleaseTokenPool.sol
> +    // it must be ensured that the remoteChainSelector can be trusted.
It's more like we're making the assumption that a message has not been tampered with in the functioning of CCIP up until this point, but if that no longer holds true well we've got bigger problems. Seems like a superfluous comment now. Will remove.

2025-01-16 16:47 UTC, RensR approved these changes

2025-01-16 16:52 UTC, 0xsuryansh approved these changes

2025-01-16 17:36 UTC, merged