chore: script to generate local ocr3 config
smartcontractkit/chainlink pull request #15808
Opened 2024-12-27 11:07 UTC by agparadiso

### Description

This pr adds a script to generate the OCR3 config for a local env
[CAPPL-356](https://smartcontract-it.atlassian.net/browse/CAPPL-356)

### Requires

### Supports

2024-12-30 10:10 UTC, ettec approved these changes, later dismissed

2025-01-06 16:53 UTC, MStreet3 commented on core/scripts/keystone/src/generate_local_ocr3_config.go
> +	publicKeys := []byte(`[
why are there hardcoded values?

2025-01-06 16:55 UTC, MStreet3 commented on core/scripts/keystone/src/generate_local_ocr3_config.go
> +	publicKeys := []byte(`[
I guess I assumed that a local setup script would accept some auth params for a set of nodes, query each of the nodes for the necessary key values, then build the `pubKeys` slice with the fetched data.

2025-01-07 15:23 UTC, chudilka1 requested changes

2025-01-07 15:23 UTC, chudilka1 commented on core/scripts/keystone/src/generate_local_ocr3_config.go
> +	publicKeys := []byte(`[
Agree. It would be nice to let the values be injected instead of code modifications per case (e.g., an example may be taken from https://github.com/smartcontractkit/chainlink/blob/develop/core/scripts/keystone/src/88_gen_ocr3_config_test.go)

2025-01-16 15:21 UTC, agparadiso commented on core/scripts/keystone/src/generate_local_ocr3_config.go
> +	publicKeys := []byte(`[
agree! lets have this as a starting point, then we can iterate and improve

2025-01-16 15:25 UTC, chudilka1 approved these changes

2025-01-16 16:15 UTC, MStreet3 approved these changes

2025-01-16 16:37 UTC, merged