Solana plugin codec implementation
smartcontractkit/chainlink pull request #15816
Opened 2024-12-30 17:09 UTC by huangzhen1997

2025-01-10 04:38 UTC, prashantkumar1982 requested changes

2025-01-10 04:38 UTC, prashantkumar1982 commented on core/capabilities/ccip/ccipsolana/commitcodec.go
> +			UsdPerUnitGas:     common.To28BytesBE(update.GasPrice.Int.Uint64()),
update.GasPrice can be empty. Plz add validation for it, similar to the one in the evm version.

2025-01-10 04:38 UTC, prashantkumar1982 commented on core/capabilities/ccip/ccipsolana/commitcodec_test.go
> +			name: "zero gas price",
as per above comment, add another case for empty gas price, which should expect error

2025-01-10 04:38 UTC, prashantkumar1982 commented on core/capabilities/ccip/ccipsolana/commitcodec_test.go
> +func BenchmarkCommitPluginCodecV1_Encode(b *testing.B) {
what are these Benchmark unused functions?

Could we have 1 test that encodes a report, decodes it back, and compares that original matches exactly the one after encoding and decoding?

2025-01-10 04:38 UTC, prashantkumar1982 commented on core/capabilities/ccip/ccipsolana/commitcodec.go
> +	if len(report.MerkleRoots) != 0 {
curious if we should do validation that there's only 1 MerkleRoot in here?

2025-01-10 04:38 UTC, prashantkumar1982 commented on core/capabilities/ccip/ccipsolana/executecodec.go
> +				DestGasAmount:     bytesToUint32(tokenAmount.DestExecData),
I'm not fully sure what format this field will be encoded to []byte as.
We should review this specific field with a CCIP team member.
I suspect if source chain is EVM, this may be encoded using abi.

2025-01-10 04:38 UTC, prashantkumar1982 commented on core/capabilities/ccip/ccipsolana/executecodec.go
> +		err := extraArgs.UnmarshalWithDecoder(decoder)
I started a thread around SolanaExtraArgs encoding scheme.
As of today, I think if EVM is the source chain, this would be encoded as abi.
We need to discuss in that thread what this should be like.

2025-01-10 04:38 UTC, prashantkumar1982 commented on core/capabilities/ccip/ccipsolana/executecodec.go
> +		binary.BigEndian.PutUint32(destData, tokenAmount.DestGasAmount)
Again, I'm a little lost on what this encoding should be like.
Need someone from CCIP to explain to us.

2025-01-10 04:38 UTC, prashantkumar1982 commented on core/capabilities/ccip/ccipsolana/executecodec.go
> +			DestTokenAddress:  cciptypes.UnknownAddress(tokenAmount.DestTokenAddress.String()),
this should be tokenAmount.DestTokenAddress.Bytes() right?

2025-01-10 04:38 UTC, prashantkumar1982 commented on core/capabilities/ccip/ccipsolana/executecodec.go
> +			Receiver:       cciptypes.UnknownAddress(executeReport.Message.Receiver.String()),
should be Bytes() instead of String()

2025-01-10 18:39 UTC, huangzhen1997 commented on core/capabilities/ccip/ccipsolana/commitcodec_test.go
> +func BenchmarkCommitPluginCodecV1_Encode(b *testing.B) {
It's for benchmarking purpose similar to what evm codec test had, it measures ns/op speed etc.

I added another benchmark for decode encoded report

2025-01-10 18:41 UTC, huangzhen1997 commented on core/capabilities/ccip/ccipsolana/commitcodec.go
> +	if len(report.MerkleRoots) != 0 {
Yes I had for execute, adding it for commit as well

2025-01-14 14:24 UTC, ilija42 commented on core/capabilities/ccip/ccipsolana/commitcodec.go
> +type CommitPluginCodecV1 struct{}
why can't we use the Solana Codec for this? Just define the IDL for these types

2025-01-14 15:30 UTC, huangzhen1997 commented on core/capabilities/ccip/ccipsolana/commitcodec.go
> +type CommitPluginCodecV1 struct{}
We could try Solana codec, @archseer suggested to use the generated [gobinding](https://github.com/smartcontractkit/chainlink/pull/15320#pullrequestreview-2521455270) for this earlier, and I also think it makes sense as the EVM codec right now is using similar approach with the generated type.

2025-01-22 22:01 UTC, huangzhen1997 commented on core/capabilities/ccip/ccipsolana/executecodec_test.go
> +		// TODO uncomment when extraargs codec implemented, right now the map is empty
Blocked by https://github.com/smartcontractkit/chainlink/pull/16016#discussion_r1926036083

2025-01-22 23:25 UTC, matYang requested changes

2025-01-22 23:25 UTC, matYang commented on core/capabilities/ccip/ccipsolana/commitcodec.go
> +			UsdPerToken: common.To28BytesBE(update.Price.Int.Uint64()),
Price has 18 decimals of precision, Uint64 caps at ~19 decimals, it's not enough precision, you can instead fill into BE bytes directly with big.Int

2025-01-22 23:25 UTC, matYang commented on core/capabilities/ccip/ccipsolana/commitcodec.go
> +			UsdPerUnitGas:     common.To28BytesBE(update.GasPrice.Int.Uint64()),
similar to above, gas price is actually uint224, you probably want to convert that to bytes directly, example:
```
    // Convert to a 28-byte (224-bit) big-endian array
    bytesVal := val.FillBytes(make([]byte, 28))
```

2025-01-23 12:59 UTC, makramkd commented on core/capabilities/ccip/ccipsolana/commitcodec_test.go
> +func TestCommitPluginCodecV1(t *testing.T) {
I just noticed that the EVM codec tests don't decode using the onchain contracts, which is probably an oversight since the exec codec does. Is there any way we can achieve the same coverage w/ this Solana encoder? Presumably the Solana contract will attempt to decode the commit report bytes into some data structure, having that covered here means we're good to go and covers an important part of the E2E flow.

2025-01-23 12:59 UTC, makramkd commented on core/capabilities/ccip/ccipsolana/executecodec_test.go
> +func TestExecutePluginCodecV1(t *testing.T) {
Ditto here re: decoding using the Solana contract.

2025-01-23 12:59 UTC, makramkd commented on core/capabilities/ccip/ccipsolana/commitcodec.go
> +			UsdPerToken: [28]uint8(update.Price.FillBytes(make([]byte, 28))),
This stores it as big-endian, is that the expected byte-order?

2025-01-23 12:59 UTC, makramkd commented on core/capabilities/ccip/ccipsolana/commitcodec.go
> +	if len(report.MerkleRoots) == 0 || len(report.MerkleRoots) > 1 {
```suggestion
	if len(report.MerkleRoots) != 1 {
```

We want exactly one merkle root right? 

Side note: why are we enforcing only one merkle root in the commit report? Is there some Solana-specific limitation for commit reports as well, meaning we can't do multi-source batching of roots? cc @winder @archseer

2025-01-23 12:59 UTC, makramkd commented on core/capabilities/ccip/ccipsolana/commitcodec.go
> +func priceHelper(input []byte) cciptypes.BigInt {
Similar note about endian-ness here, is the input in little or big endian? I believe `SetBytes` sets it in big-endian https://pkg.go.dev/math/big#Int.SetBytes

2025-01-23 12:59 UTC, makramkd commented on core/capabilities/ccip/ccipsolana/executecodec.go
> +	if len(report.ChainReports) == 0 || len(report.ChainReports) > 1 {
```suggestion
	if len(report.ChainReports) != 1 {
```

2025-01-23 12:59 UTC, makramkd commented on core/capabilities/ccip/ccipsolana/executecodec.go
> +		// currently only allow committing one message at a time
```suggestion
		// currently only allow executing one message at a time
```

2025-01-23 12:59 UTC, makramkd commented on core/capabilities/ccip/ccipsolana/executecodec.go
> +		// currently only allow committing one message at a time
If this is the case shouldn't we error if there is > 1 message?

2025-01-23 12:59 UTC, makramkd commented on core/capabilities/ccip/ccipsolana/executecodec.go
> +	ag_solanago "github.com/gagliardetto/solana-go"
double import, can remove one of them

2025-01-23 12:59 UTC, makramkd commented on core/capabilities/ccip/ccipsolana/executecodec.go
> +	}
We should only have an offchain token data if there are tokens as part of the message, perhaps that can be validated

2025-01-23 12:59 UTC, makramkd commented on core/capabilities/ccip/ccipsolana/executecodec.go
> +		}
Shouldn't logic like this be in the extra args codec instead of here?

2025-01-23 12:59 UTC, makramkd commented on core/capabilities/ccip/ccipsolana/executecodec.go
> +				DestGasAmount:     bytesToUint32(tokenAmount.DestExecData),
Similar comment to the other one on the extra args, feels like the extra args codec should be used here to marshal into the expected solana format

2025-01-23 12:59 UTC, makramkd commented on core/capabilities/ccip/ccipsolana/executecodec.go
> +func parseExtraArgsMap(input map[string]any) (ccip_router.SolanaExtraArgs, error) {
Put in the extra args codec

2025-01-23 17:52 UTC, huangzhen1997 commented on core/capabilities/ccip/ccipsolana/executecodec.go
> +		}
The extra args [codec](https://github.com/smartcontractkit/chainlink/pull/16016) is used for constructing the ExtraArgsDecoded map when required by the codec. From my understanding, if the map is needed based on the source chain, we can customize its handling to build the extra arguments during encoding.

2025-01-23 17:55 UTC, huangzhen1997 commented on core/capabilities/ccip/ccipsolana/executecodec.go
> +				DestGasAmount:     bytesToUint32(tokenAmount.DestExecData),
This part will be refactor after the DestExecData [changes](https://chainlink-core.slack.com/archives/C0779R3AH8R/p1737640327593489?thread_ts=1737499687.872009&cid=C0779R3AH8R)

2025-01-23 21:55 UTC, huangzhen1997 commented on core/capabilities/ccip/ccipsolana/executecodec.go
> +		}
I need to construct a `ccip_router.SolanaExtraArgs` from this decoded map, so I can return the borsh encode into bytes

2025-01-24 03:04 UTC, huangzhen1997 commented on core/capabilities/ccip/ccipsolana/commitcodec.go
> +func priceHelper(input []byte) cciptypes.BigInt {
Yeah I thought about this because Borsh encoding use little-endian. But I wonder whether this matter, as the ccip_router.TokenPriceUpdate only keeps bytes representation, and the codec decoder use big-endian when decoding.

2025-01-24 23:18 UTC, prashantkumar1982 requested changes
I think everywhere in SVM codecs, we ought to use LittleEndian encoding, as onchain decoding/encoding on Solana will use LE.

2025-01-24 23:18 UTC, prashantkumar1982 commented on core/capabilities/ccip/ccipsolana/commitcodec.go
> +type CommitPluginCodecV1 struct{}
This was a general topic earlier, where we said lets use the Codec for both EVM and Solana, to make this code here chain-abstract.
But it was more work, and complex, so we abandoned that approach to be looked at at a longer term.

2025-01-24 23:18 UTC, prashantkumar1982 commented on core/capabilities/ccip/ccipsolana/commitcodec.go
> +func priceHelper(input []byte) cciptypes.BigInt {
SVM codec should use little endian right?
This function seems to assume input is BE, while I think it should be LE

2025-01-24 23:18 UTC, prashantkumar1982 commented on core/capabilities/ccip/ccipsolana/commitcodec.go
> +func priceHelper(input []byte) cciptypes.BigInt {
nit: This is used in executecodec, but defined here. Can you move it to the execute go file?
Also, could it be renamed to decodeBigIntFrombytesBE/decodeBigIntFrombytesLE, whichever we end up using?

2025-01-24 23:18 UTC, prashantkumar1982 commented on core/capabilities/ccip/ccipsolana/executecodec.go
> +	copy(b[32-len(raw):], raw) // Right-align and zero-pad
I think we should convert to LE and rename func to signal LE

2025-01-24 23:18 UTC, prashantkumar1982 commented on core/capabilities/ccip/ccipsolana/executecodec.go
> +				Amount:            bigIntToBytes32(tokenAmount.Amount),
As per latest solana go code, this should be LE:
https://github.com/smartcontractkit/chainlink-ccip/blob/a0491362f884640d8734bd1d5eae5d25a394a5ce/chains/solana/gobindings/ccip_router/types.go#L943-L945

https://github.com/smartcontractkit/chainlink-ccip/blob/a0491362f884640d8734bd1d5eae5d25a394a5ce/chains/solana/gobindings/ccip_router/types.go#L708

Also, you might need to refresh and use Any2SVMTokenTransfer instead of Any2SolanaTokenTransfer

2025-01-24 23:22 UTC, huangzhen1997 commented on core/capabilities/ccip/ccipsolana/commitcodec.go
> +func priceHelper(input []byte) cciptypes.BigInt {
Yes this is outdated code, just about to remove it and use LE for execute codec as well

2025-01-24 23:32 UTC, huangzhen1997 commented on core/capabilities/ccip/ccipsolana/commitcodec.go
> +func priceHelper(input []byte) cciptypes.BigInt {
Agreed, already converted to LE

2025-01-25 01:47 UTC, prashantkumar1982 commented on core/capabilities/ccip/ccipsolana/executecodec.go
> +		case "ComputeUnits":
Is the string case sensitive here?
Atleast in the EVM onchain contracts, I see the values are camel case:
https://github.com/smartcontractkit/chainlink/blob/4e284976ea8ca7c0e355efce6336742d70918ac2/contracts/src/v0.8/ccip/libraries/Client.sol#L57-L63

Might be better to just do a case insensitive matching here.

Also note that in EVM contracts, we have 2 more fields, allowOutOfOrderExecution and tokenReceiver.

We need to ask Solana onchain team to add these 2 new types too.

2025-01-25 01:47 UTC, prashantkumar1982 commented on core/capabilities/ccip/ccipsolana/executecodec.go
> +		}
Add a default case too, and return error from there.
We shouldn't ever see any unknown field here.

2025-01-25 01:47 UTC, prashantkumar1982 commented on core/capabilities/ccip/ccipsolana/executecodec.go
> +func parseExtraArgsMap(input map[string]any) (ccip_router.SVMExtraArgs, error) {
Maybe another ticket/PR, but we would ideally also like to do the same on the EVM codec eventually.

2025-01-25 01:47 UTC, prashantkumar1982 commented on core/capabilities/ccip/ccipsolana/executecodec.go
> +		family, err := chainsel.GetSelectorFamily(uint64(chainReport.SourceChainSelector))
nit: rename to sourceChainFamily

2025-01-25 01:47 UTC, prashantkumar1982 commented on core/capabilities/ccip/ccipsolana/executecodec.go
> +			//TokenReceiver: solana.PublicKeyFromBytes(msg.Receiver),
I believe it is this one: https://github.com/smartcontractkit/chainlink/blob/4e284976ea8ca7c0e355efce6336742d70918ac2/contracts/src/v0.8/ccip/libraries/Client.sol#L61

But we should confirm with EVM and Solana onchain team

2025-01-25 01:47 UTC, prashantkumar1982 commented on core/capabilities/ccip/ccipsolana/executecodec.go
> +		destData := make([]byte, 4)
I assume this will later on start using the new map that you created?

2025-01-25 01:47 UTC, prashantkumar1982 commented on core/capabilities/ccip/ccipsolana/executecodec.go
> +func parseExtraArgsMap(input map[string]any) (ccip_router.SVMExtraArgs, error) {
FYI, this function will also be used in the MessageHasher.

2025-01-29 22:24 UTC, prashantkumar1982 commented on core/capabilities/ccip/ccipsolana/executecodec.go
> +		case "destgasamount":
This string is also used in the evmDestExecDataKey in the evm codec, on your other PR.
It will be good to define this string somewhere common place, and refer to it from both evm and solana codecs.

2025-01-29 22:24 UTC, prashantkumar1982 commented on core/capabilities/ccip/ccipsolana/executecodec.go
> +			// we only need the keys to construct SVMExtraArgs, other keys can be skipped without return errors
Hmm, I think the Encode() would need to also include the Accounts.
Atleast we need Accounts for MessageHasher.

2025-01-29 22:24 UTC, prashantkumar1982 commented on core/capabilities/ccip/ccipsolana/commitcodec_test.go
> +func TestCommitPluginCodecV1(t *testing.T) {
Hmm, I think it might be possible.
In Solana, we have generated go bindings for all onchain types.
So technically we could construct the onchain types via structs, and encode them via go encoders.
Then, we compare that those encoded types are same as what our offchain code calculates.
Agreed, these will be a good e2e tests.
Will talk to @huangzhen1997 on this.

2025-01-29 22:32 UTC, huangzhen1997 commented on core/capabilities/ccip/ccipsolana/executecodec.go
> +			// we only need the keys to construct SVMExtraArgs, other keys can be skipped without return errors
Yes, I added and mentioned in message hasher PR.

2025-01-29 23:29 UTC, huangzhen1997 commented on core/capabilities/ccip/ccipsolana/executecodec.go
> +		case "destgasamount":
Yes it's defined in https://github.com/smartcontractkit/chainlink/pull/16016, we can update this once merged.

2025-01-31 19:28 UTC, prashantkumar1982 commented on core/capabilities/ccip/ccipsolana/commitcodec_test.go
> +		decode, err := commitCodec.Decode(testutils.Context(t), buf.Bytes())
Could we also do the reverse for the same data?
I mean encode with commitCodec, and then decode with borsch decoder?

2025-01-31 19:28 UTC, prashantkumar1982 commented on core/capabilities/ccip/ccipsolana/executecodec_test.go
> +		decode, err := executeCodec.Decode(testutils.Context(t), buf.Bytes())
same reverse comment for execute codec too

2025-01-31 21:20 UTC, prashantkumar1982 approved these changes

2025-02-01 00:18 UTC, winder commented on core/scripts/go.mod
These dependency changes seem unintentional

2025-02-03 19:48 UTC, makramkd approved these changes

2025-02-03 20:46 UTC, winder approved these changes

2025-02-03 21:25 UTC, merged