CCIP-4687 Support Solana in the FeeQuoter
smartcontractkit/chainlink pull request #15811
Opened 2024-12-27 18:47 UTC by jhweintraub

Add Solana Support to the FeeQuoter by adding

1. New Family Chain Selector `CHAIN_FAMILY_SELECTOR_SOL`
2. New `SOL_EXTRA_EXTRA_ARGS_V1_TAG`
3. Adding parsing support and control flow logic for both of the above.

2024-12-30 18:16 UTC, agusaldasoro commented on contracts/src/v0.8/ccip/FeeQuoter.sol
> +    }
It's okay to remove this validation, as we are not failing in Solana contracts
```suggestion
```

2024-12-30 18:16 UTC, agusaldasoro commented on contracts/src/v0.8/ccip/libraries/Internal.sol
> +  function _validateSolAddress(
this should run for every account in extraArgs right?

2025-01-03 14:37 UTC, agusaldasoro requested changes

2025-01-03 14:37 UTC, agusaldasoro commented on contracts/src/v0.8/ccip/FeeQuoter.sol
> +    if (messageDataLengthBytes != 0 && SolExtraArgs.accounts.length == 0) revert SolExtraArgsMustBeProvided();
We need to remove this validation as well, as we need to support executing a message with data.lenght == 0
```suggestion
```

2025-01-06 13:23 UTC, RensR commented on contracts/src/v0.8/ccip/FeeQuoter.sol
> +    if (destChainConfig.chainFamilySelector == Internal.CHAIN_FAMILY_SELECTOR_EVM) {
Prefer `if return` over `if else`

2025-01-06 13:23 UTC, RensR commented on contracts/src/v0.8/ccip/FeeQuoter.sol
> +  function _parseUnvalidatedSolExtraArgsFromBytes(
probably can be part of `_parseSolExtraArgsFromBytes`

2025-01-06 13:23 UTC, RensR commented on contracts/src/v0.8/ccip/FeeQuoter.sol
> +    bytes memory argsData = extraArgs[4:];
can inline

2025-01-06 13:23 UTC, RensR commented on contracts/src/v0.8/ccip/FeeQuoter.sol
> +    Client.SolExtraArgsV1 memory solExtraArgs = abi.decode(argsData, (Client.SolExtraArgsV1));
can return, don't need to assign

2025-01-06 13:23 UTC, RensR commented on contracts/src/v0.8/ccip/FeeQuoter.sol
> +      (convertedExtraArgs, isOutOfOrderExecution) = _processChainFamilySelector(destChainSelector, data, extraArgs);
Only the length is ever used, it's a lot cheaper to pass in a single length property

2025-01-06 13:23 UTC, RensR commented on contracts/src/v0.8/ccip/FeeQuoter.sol
> +      isOutOfOrderExecution = parsedExtraArgs.allowOutOfOrderExecution;
prefer returning over nesting

2025-01-06 13:23 UTC, RensR commented on contracts/src/v0.8/ccip/FeeQuoter.sol
> +    return (convertedExtraArgs, isOutOfOrderExecution);
should error if not returned by here

2025-01-06 13:23 UTC, RensR commented on contracts/src/v0.8/ccip/libraries/Client.sol
> +  struct SolanaAccountMeta {
This feels pretty expensive as we use 33 bytes per account. We could consider the writability as a bool encoding into a digit?

2025-01-06 13:23 UTC, RensR commented on contracts/src/v0.8/ccip/libraries/Internal.sol
> +  function _validateSolAddress(
They are already typed as bytes32 so not needed

2025-01-06 15:27 UTC, jhweintraub commented on contracts/src/v0.8/ccip/FeeQuoter.sol
> +    Client.SolExtraArgsV1 memory solExtraArgs = abi.decode(argsData, (Client.SolExtraArgsV1));
Do we not need to check the validity of the computeUnits?

2025-01-06 15:32 UTC, jhweintraub commented on contracts/src/v0.8/ccip/FeeQuoter.sol
> +      (convertedExtraArgs, isOutOfOrderExecution) = _processChainFamilySelector(destChainSelector, data, extraArgs);
Now that we don't have to check for message length though we can remove this anyways

2025-01-10 10:35 UTC, makramkd commented on contracts/src/v0.8/ccip/libraries/Client.sol
> +  }
Docs on these fields w/ links to Solana docs would be nice for newbies

2025-01-10 10:35 UTC, makramkd commented on contracts/src/v0.8/ccip/FeeQuoter.sol
> +      // TODO: With the addition of Solana and other Non-evm Chains, family selector is not validated.
Stale comment I think, its validated above in _processChainFamilySelector?

2025-01-10 10:35 UTC, makramkd commented on contracts/src/v0.8/ccip/libraries/Internal.sol
> +  bytes4 public constant CHAIN_FAMILY_SELECTOR_SOL = 0x2d4dfc1c;
Not that I don't trust the comment above, but maybe we can have a test that asserts that 0x2d4dfc1c is truly == to `bytes4(keccak256("CCIP ChainFamilySelector SOL"));` 😛

2025-01-14 03:38 UTC, prashantkumar1982 commented on contracts/src/v0.8/ccip/libraries/Client.sol
> +  struct SVMExtraArgsV1 {
I'm not an expert on onchain, but shouldn't this type match the onchain type used in Solana as per here:
**https://github.com/smartcontractkit/chainlink-ccip/blob/679d6f555e8dc295f92f2f385ce01ba9746968be/chains/solana/contracts/programs/ccip-router/src/messages.rs#L45-L49**

Or is the expectation that Solana onchain code will be later changed to match this?

2025-01-14 07:36 UTC, RensR commented on contracts/src/v0.8/ccip/libraries/Client.sol
> +  struct SVMExtraArgsV1 {
We're going with SVM over Sol or Solana, the Solana team still needs to change it. They should match

2025-01-14 07:39 UTC, RensR commented on contracts/src/v0.8/ccip/libraries/Client.sol
> +    address tokenReceiver;
Should be bytes32 since it's known to be solana

2025-01-14 08:10 UTC, 0xsuryansh commented on contracts/src/v0.8/ccip/libraries/Client.sol
> +    address tokenReceiver;
https://github.com/smartcontractkit/chainlink/pull/15811/commits/2ecb33b446702217416e1d7dd0264a4c844629f4

2025-01-14 10:09 UTC, RensR commented on contracts/src/v0.8/ccip/FeeQuoter.sol
> +  using EnumerableSet for EnumerableSet.Bytes32Set;
Is this used anywhere?

2025-01-14 10:09 UTC, RensR commented on contracts/src/v0.8/ccip/FeeQuoter.sol
> +  event ChainFamilySelectorModified(bytes4 chainFamilySelector, bool isAdded);
nit: we use updated instead of modified

2025-01-14 10:09 UTC, RensR commented on contracts/src/v0.8/ccip/FeeQuoter.sol
> +  struct GetValidatedFeeLocalVars {
Let's avoid this if we can, there's a chance the issue is solved after my PR. If we do have to do this, probably more gas efficient to not put every single thing into it

2025-01-14 10:09 UTC, RensR commented on contracts/src/v0.8/ccip/FeeQuoter.sol
> +    GetValidatedFeeLocalVars memory v;
variable names are free in Solidity! Avoid single char vars

2025-01-14 10:09 UTC, RensR commented on contracts/src/v0.8/ccip/FeeQuoter.sol
> +  /// call is needed to a library function for address validation.
What does this comment try to say? There's literally a call to a lib for SVM?

2025-01-14 10:09 UTC, RensR commented on contracts/src/v0.8/ccip/FeeQuoter.sol
> +    }
let's revert on unknown chain selector

2025-01-14 10:09 UTC, RensR commented on contracts/src/v0.8/ccip/FeeQuoter.sol
> +    if (destChainConfig.chainFamilySelector == Internal.CHAIN_FAMILY_SELECTOR_EVM) {
@jhweintraub Why was this resolved but not fixed?

2025-01-14 10:09 UTC, RensR commented on contracts/src/v0.8/ccip/FeeQuoter.sol
> +      gasLimit = destChainConfig.defaultTxGasLimit;
We should revert in invalid input, not just let it pass

2025-01-14 10:09 UTC, RensR commented on contracts/src/v0.8/ccip/FeeQuoter.sol
> +    Client.SVMExtraArgsV1 memory svmExtraArgs;
nit: could use the return declaration over a new value

2025-01-14 10:09 UTC, RensR commented on contracts/src/v0.8/ccip/FeeQuoter.sol
> +      _validateDestFamilyAddress(destChainConfig.chainFamilySelector, receiver);
Does this not break EVM?

2025-01-14 10:09 UTC, RensR commented on contracts/src/v0.8/ccip/test/feeQuoter/FeeQuoterSetup.t.sol
> +  function _generateEmptyMessage2Sol() public view returns (Client.EVM2AnyMessage memory) {
2SVM

2025-01-14 10:09 UTC, RensR commented on contracts/src/v0.8/ccip/FeeQuoter.sol
> +    } else if (destChainConfig.chainFamilySelector == Internal.CHAIN_FAMILY_SELECTOR_SVM) {
you can remove all the `else`s because we return in every if

2025-01-14 10:09 UTC, RensR commented on contracts/src/v0.8/ccip/FeeQuoter.sol
> +    if (extraArgs.length == 0) {
This is wrong I think, SVM always required extraArgs because it always needs OOO. It should revert here

2025-01-14 20:32 UTC, 0xsuryansh commented on contracts/src/v0.8/ccip/FeeQuoter.sol
> +  /// call is needed to a library function for address validation.
I think this is a stale comment, will remove this

2025-01-15 00:17 UTC, 0xsuryansh commented on contracts/src/v0.8/ccip/FeeQuoter.sol
> +    if (extraArgs.length == 0) {
You mean we should include  a field `allowOutOfOrderExecution` in 

```
struct SVMExtraArgsV1 {
    uint32 computeUnits;
    uint64 accountIsWritableBitmap;
    bytes32 tokenReceiver;
    bytes32[] accounts;
  }
```

2025-01-15 06:43 UTC, 0xsuryansh commented on contracts/src/v0.8/ccip/FeeQuoter.sol
> +    GetValidatedFeeLocalVars memory v;
Ack, I think we won't need this struct one we merge EIP-7623 PR

2025-01-15 06:49 UTC, 0xsuryansh commented on contracts/src/v0.8/ccip/FeeQuoter.sol
> +  using EnumerableSet for EnumerableSet.Bytes32Set;
removed

2025-01-15 06:50 UTC, 0xsuryansh commented on contracts/src/v0.8/ccip/FeeQuoter.sol
> +  event ChainFamilySelectorModified(bytes4 chainFamilySelector, bool isAdded);
Thanks, fixed this

2025-01-15 09:29 UTC, RensR commented on contracts/src/v0.8/ccip/FeeQuoter.sol
> +    if (extraArgs.length == 0) {
Yes

2025-01-16 14:16 UTC, jhweintraub commented on contracts/src/v0.8/ccip/FeeQuoter.sol
> +  ) internal view returns (bytes memory, bool) {
nit: add names to return values (bytes memory encodedExtraArgs, bool isOutOfOrderExecution) and that true is hard coded into solana since out of order execution is always enabled.

2025-01-16 14:21 UTC, jhweintraub commented on contracts/src/v0.8/ccip/FeeQuoter.sol
> +      _validateDestFamilyAddress(chainFamilySelector, onRampTokenTransfers[i].destTokenAddress, 1);
nit: Can we add a comment about how this hard coded gas limit is acceptable for Solana since this loop is already being called in the context of a token transfer, and therefore destTokenAddress does need to be checked for validity on SVM?

2025-01-16 14:26 UTC, jhweintraub commented on contracts/src/v0.8/ccip/onRamp/OnRamp.sol
> +    // Using newMessage.data prevents a stack too deep error.
nit: remove .data since it's not used after this or the whole line can probably just go too

2025-01-16 14:29 UTC, agusaldasoro commented on contracts/src/v0.8/ccip/FeeQuoter.sol
> +      revert MessageGasLimitTooHigh();
Is it possible here to revert with a Solana Custom error for compute units?

2025-01-16 14:29 UTC, agusaldasoro commented on contracts/src/v0.8/ccip/libraries/Client.sol
> +    bytes32 tokenReceiver;
This means that `messageReceiver == msg.header.receiver == receiverProgramId` && `tokenReceiver == msg.extraArgs.tokenReceiver`? 
FYI: @aalu1418

2025-01-16 15:20 UTC, aalu1418 commented on contracts/src/v0.8/ccip/libraries/Client.sol
> +    bytes32 tokenReceiver;
yup!

2025-01-16 17:20 UTC, huangzhen1997 commented
I don't see the ABI is updated [here](https://github.com/smartcontractkit/chainlink/blob/f9dd7e13bc952e1f006f7e5c663b0953aa565cce/core/gethwrappers/ccip/generated/message_hasher/message_hasher.go#L74), are we supposed to update it with the new `decodeSVMExtraArgsV1` ?

2025-01-16 20:26 UTC, 0xsuryansh commented on contracts/src/v0.8/ccip/FeeQuoter.sol
> +      if (gasLimit > 0 && svmAddress == bytes32(0)) {
Can change the `gasLimit` param to a bool `isZeroAddressVaid` ? This param will indicate if the function should revert when destAddress is zero

2025-01-16 20:26 UTC, 0xsuryansh commented on contracts/src/v0.8/ccip/FeeQuoter.sol
> +      if (gasLimit > 0 && svmAddress == bytes32(0)) {
Personally doesn't look clean to me to pass a gasLimitAddress to a function which validates address for family. Suggest if we can do this validation somewhere else

2025-01-16 20:26 UTC, 0xsuryansh commented on contracts/src/v0.8/ccip/FeeQuoter.sol
> +    uint256 packedGasPrice = _getValidatedGasPrice(destChainSelector, destChainConfig.gasPriceStalenessThreshold);
Will change this back to 224

2025-01-16 21:02 UTC, prashantkumar1982 commented
> I don't see the ABI is updated [here](https://github.com/smartcontractkit/chainlink/blob/f9dd7e13bc952e1f006f7e5c663b0953aa565cce/core/gethwrappers/ccip/generated/message_hasher/message_hasher.go#L74), are we supposed to update it with the new `decodeSVMExtraArgsV1` ?

Yes, for EvmExtraArgsv1 and EVMExtraArgsv2, I see there is this code in the solidity contracts: https://github.com/smartcontractkit/chainlink/blob/12af1de88238e0e918177d6b5622070417f48adf/contracts/src/v0.8/ccip/test/helpers/MessageHasher.sol#L67-L90

That ends up creating a lot of generated code in MessageHasher.go, which offchain code uses.
We need that for SVMExtraArgsV1 too.

2025-01-17 02:18 UTC, 0xsuryansh commented on contracts/src/v0.8/ccip/FeeQuoter.sol
> +      revert MessageGasLimitTooHigh();
Added https://github.com/smartcontractkit/chainlink/pull/15811/commits/5b7720e653265979a57494053b76c006eee573c7#diff-1859122b5ff5261692222f5ba921ee9108438593b0664e5aba8d573d866f27aaR952

2025-01-17 16:37 UTC, agusaldasoro approved these changes

2025-01-17 16:38 UTC, 0xsuryansh approved these changes

2025-01-18 07:03 UTC, merged

2025-01-20 08:09 UTC, 0xsuryansh commented
> > I don't see the ABI is updated [here](https://github.com/smartcontractkit/chainlink/blob/f9dd7e13bc952e1f006f7e5c663b0953aa565cce/core/gethwrappers/ccip/generated/message_hasher/message_hasher.go#L74), are we supposed to update it with the new `decodeSVMExtraArgsV1` ?

Added here https://github.com/smartcontractkit/chainlink/pull/15983