Remove extraneous cleanupt/setup part of prepublishOnly
smartcontractkit/chainlink pull request #3673
Opened 2020-11-19 22:43 UTC by j16r

2020-11-20 20:29 UTC, HenryNguyen5 approved these changes

2020-11-20 20:30 UTC, HenryNguyen5 requested changes
We still want the clean step

2020-11-20 20:43 UTC, j16r commented
Why is the clean step needed, isn't it a fresh environment every time?

2020-11-30 20:15 UTC, HenryNguyen5 commented
> Why is the clean step needed, isn't it a fresh environment every time?

The publish is run on personal machines, we dont have CD setup for it atm

2020-11-30 20:27 UTC, closed without merging