Add password strength check
smartcontractkit/chainlink pull request #3789
Opened 2020-12-16 18:39 UTC by spooktheducks

2020-12-16 20:02 UTC, j16r commented on core/cmd/key_store_authenticator.go
> +	// Must comprise at least 3 of:
I'd kind of lean towards NIST guidelines on this: https://stealthbits.com/blog/nist-password-guidelines/

> Complexity requirements should not be used, ex. requiring special characters, numbers, uppercase, etc.

2020-12-17 09:27 UTC, samsondav commented on core/cmd/key_store_authenticator.go
> +	// Must comprise at least 3 of:
I agree with @j16r.

A simple length requirement is fine, because a long sentence/passphrase can be just as secure if not more secure.

2021-02-12 22:40 UTC, spooktheducks commented on core/cmd/key_store_authenticator.go
> +	// Must comprise at least 3 of:
This was on the recommendation of our auditors ¯\\\_(ツ)\_/¯

2021-02-13 02:45 UTC, samsondav approved these changes

2021-02-13 02:45 UTC, samsondav requested changes

2021-02-13 02:45 UTC, samsondav commented on core/cmd/remote_client.go
> +	// return url.PathEscape(strings.TrimSpace(password))
commented code

2021-02-16 16:30 UTC, samsondav approved these changes

2021-02-16 16:54 UTC, merged