Staleness Validation is UpkeepCompatible
smartcontractkit/chainlink pull request #3825
Opened 2021-01-05 13:12 UTC by alexroan

2021-01-05 17:19 UTC, alexroan commented on evm-contracts/src/v0.7/dev/StalenessFlaggingValidator.sol
> +  function check(address[] calldata aggregators) external view returns (address[] memory) {
`check` and `update` are essentially type-explicit versions of the new Keeper functions. There's an open question as to whether we should remove them or not.

2021-01-07 15:23 UTC, se3000 requested changes

2021-01-07 15:23 UTC, se3000 commented on evm-contracts/src/v0.7/dev/StalenessFlaggingValidator.sol
> +  function performUpkeep(bytes calldata data) external override {
Could you make this work by calling the `update` method? They are almost identical.

2021-01-13 06:05 UTC, se3000 approved these changes

2021-01-13 09:38 UTC, merged