175686973 remove cli http status codes
smartcontractkit/chainlink pull request #3838
Opened 2021-01-08 22:00 UTC by foravneet

Remove status codes from cli error messages
https://www.pivotaltracker.com/n/projects/2441917/stories/175686973

2021-01-08 22:59 UTC, spooktheducks requested changes
Just a couple of minor changes and then I think we'll be good to go.

2021-01-08 22:59 UTC, spooktheducks commented on core/cmd/remote_client_test.go
> +	assert.EqualError(t, client.TriggerPipelineRun(c), "Internal Server Error; no job found with id 1 (most likely it was deleted)")
Let's also remove the `Internal Server Error; ` text as well

2021-01-08 22:59 UTC, spooktheducks commented on core/cmd/remote_client.go
> +var errUnauthorized = errors.New(http.StatusText(http.StatusUnauthorized))
Seems like it would be good to include an explanation about how to log in to the node (something about `chainlink admin login`)

2021-01-09 07:35 UTC, closed without merging

2021-01-09 07:35 UTC, foravneet commented
Creating new PR with suggested changes