Log debug when stats pusher writes
smartcontractkit/chainlink pull request #3940
Opened 2021-02-08 21:28 UTC by rupurt

Currently the explorer client only logs information when there

2021-02-09 17:21 UTC, samsondav requested changes

2021-02-09 17:21 UTC, samsondav commented on core/services/synchronization/explorer_client.go
> +	logger.Debugf("websocketStatsPusher successfully wrote message type %v", messageType)
```suggestion
	logger.Debugw("websocketStatsPusher successfully wrote message", "messageType", messageType, "message", message)
```

2021-02-11 01:35 UTC, se3000 approved these changes

2021-02-11 02:15 UTC, se3000 approved these changes

2021-02-11 02:15 UTC, merged