remove user seed from VRF consumer required params
smartcontractkit/chainlink pull request #4096
Opened 2021-03-19 05:39 UTC by se3000

2021-03-22 09:41 UTC, samsondav submitted a review, later dismissed

2021-03-25 10:38 UTC, samsondav submitted a review, later dismissed

2021-04-05 14:10 UTC, kaleofduty commented on evm-contracts/src/v0.6/VRFConsumerBase.sol
> +   * Given that it adds very little security, we have removed it from usage
```suggestion
   * Given that it adds no security, and can easily lead to misunderstandings, we have removed it from usage
```

2021-04-06 11:14 UTC, alexroan requested changes

2021-04-06 11:14 UTC, alexroan commented on evm-contracts/src/v0.6/VRFConsumerBase.sol
> +  uint256 constant private USER_SEED_PLACEHOLDER = 0;
These changes need to be applied to the 0.7 and 0.8 `VRFConsumerBase` also.

2021-06-01 18:06 UTC, coventry approved these changes

2021-06-02 02:16 UTC, merged