Add mock oracle contract
smartcontractkit/chainlink pull request #4133
Opened 2021-03-29 14:41 UTC by PatrickAlphaC

So that we can test API calls effectively. It's a little different from the main oracle contract, in that it allows the contract to call

`mockOracle.fulfillOracleRequest(requestId, get_data, {from: User)`

When testing, instead of having to hash the result as done in the main oracle contract.

addresses #4095

2021-03-31 21:09 UTC, se3000 submitted a review, later dismissed

2021-04-01 12:44 UTC, alexroan requested changes
Just a few styling fixes.

2021-04-01 12:44 UTC, alexroan commented on evm-contracts/src/v0.6/tests/MockOracle.sol
> +  constructor(address _link)
Separate line for parameter
```suggestion
  constructor(
    address _link
  )
```

2021-04-01 12:44 UTC, alexroan commented on evm-contracts/src/v0.6/tests/MockOracle.sol
> +    returns (bool)
Separate line per return value.
```suggestion
    returns (
      bool
    )
```

2021-04-01 12:44 UTC, alexroan commented on evm-contracts/src/v0.6/tests/MockOracle.sol
> +    returns (address)
Separate line per return value.
```suggestion
    returns (
      address
    )
```

2021-04-01 12:44 UTC, alexroan commented on evm-contracts/src/v0.6/tests/MockOracle.sol
> +  modifier isValidRequest(bytes32 _requestId) {
Separate line per parameter.
```suggestion
  modifier isValidRequest(
    bytes32 _requestId
  ) {
```

2021-04-01 12:44 UTC, alexroan commented on evm-contracts/src/v0.6/tests/MockOracle.sol
> +  modifier checkCallbackAddress(address _to) {
Separate line per parameter.
```suggestion
  modifier checkCallbackAddress(
    address _to
  ) {
```

2021-04-01 20:15 UTC, alexroan approved these changes

2021-04-01 20:15 UTC, merged

2021-04-01 21:15 UTC, PatrickAlphaC commented
yyyyyyeessssss