Bugfix: Don't allow multiple subscriptions for the same runlog job
smartcontractkit/chainlink pull request #4289
Opened 2021-04-27 18:39 UTC by connorwstein

Arose from the following scenario:
1. We read too much from the geth websocket
2. Leads to errors in many places, one of which is the head tracker itself "Error in new head subscription, unsubscribed: websocket: read limit exceeded"
3. We resubscribe with subscribeToHead, which triggers a new Connect call on all head trackables including the jobSubscriber
4. The jobSubscribers Connect will call AddJob again for all the jobs which creates new subscriptions. AddJob does NOT currently check if it already has a subscription for that job, just overwrites it
5. The listenToLogs goroutines which were spawned for the orginal call to AddJob successfully reconnect and so now we have multiple subscriptions which will fire when a log comes in for the same job

2021-04-27 21:08 UTC, samsondav requested changes
Seconded JB's request for a test.

Also, is this thread-safe?

2021-04-28 14:57 UTC, connorwstein commented
> Seconded JB's request for a test.
Added 
> Also, is this thread-safe?
It wasn't, although AddJob isn't called from multiple goroutines. I added the locking anyways

2021-04-28 15:11 UTC, j16r approved these changes

2021-04-28 15:15 UTC, samsondav approved these changes
Nice one

2021-04-28 15:16 UTC, samsondav commented on core/services/job_subscriber.go
> +	js.jobsMutex.Lock()
Could be an RLock

2021-04-28 15:23 UTC, samsondav approved these changes

2021-04-28 15:33 UTC, merged