ValidatorProxy extra additions
smartcontractkit/chainlink pull request #4301
Opened 2021-04-29 14:58 UTC by alexroan

2021-04-29 15:11 UTC, kaleofduty commented on CODEOWNERS
> +/evm-contracts/ @alexroan @se3000 @kaleofduty
please have mercy, think about my poor github notifications

2021-04-30 14:55 UTC, kaleofduty commented
Can we enforce that the proposed aggregator != the current aggregator and that the proposed validator != the current validator?
In particular if proposed validator == current validator, this could have some weird effects where validate is called twice.

2021-04-30 15:09 UTC, kaleofduty commented
Also worth noting that there could be weird re-entrancy behavior if the validator and aggregator are the same contract. (Even longer re-entrancy loops are also possible.) However, since that contract would have to be written in a pretty strange way and it seems less likely that `owner` would make that mistake, I'm leaning towards not adding a check or mutex. 
What are your thoughts @se3000 @alexroan ?

2021-05-03 14:00 UTC, se3000 commented
I'm leaning towards no mutex, because we'd have to explicitly go out of our way to our way to write a contract that recalls the Validator interface. Seems very hard to do accidentally, at least in the use case we're currently considering. The downside there is that we have to remember that, but we could just document it for now.

2021-05-04 10:26 UTC, alexroan commented
Seems like we're on the same page regarding the aggregator != validator check / mutex.

2021-05-05 08:56 UTC, kaleofduty requested changes

2021-05-05 08:56 UTC, kaleofduty commented on evm-contracts/src/v0.8/dev/ValidatorProxy.sol
> +    currentValidatorAddress.call(
Please document why you're using raw calls here

2021-05-05 08:56 UTC, kaleofduty commented on evm-contracts/src/v0.8/dev/ValidatorProxy.sol
> +          validateSelector,
tiny nit: I find this a little cleaner
```suggestion
          AggregatorValidatorInterface.validate.selector,
```

2021-05-05 08:56 UTC, kaleofduty commented on evm-contracts/src/v0.8/dev/ValidatorProxy.sol
> +        validateSelector,
tiny nit: I find this a little cleaner
```suggestion
        AggregatorValidatorInterface.validate.selector,
```

2021-05-05 08:58 UTC, kaleofduty commented
Please add a `dev` comment about our reasoning re  reentrancy on validate

2021-05-07 11:19 UTC, kaleofduty commented
Could you add a typeAndVersion, @alexroan ?

2021-05-07 11:21 UTC, kaleofduty commented on evm-contracts/src/v0.8/dev/ValidatorProxy.sol
> +   * @dev If the `aggregator` and `validator` are the same contract, this could exhibit reentrancy behavior.
```suggestion
   * @dev If the `aggregator` and `validator` are the same contract or collude, this could exhibit reentrancy behavior.
```

2021-05-07 11:27 UTC, kaleofduty commented
In the typical case, there won't be a proposedAggregator set.
We can save ~2k gas on each transmission by modifying this check at the top of `validate`
```
    address currentAggregator = s_currentAggregator.target;
    address proposedAggregator = s_proposedAggregator;
    require(msg.sender == currentAggregator || msg.sender == proposedAggregator, "Not a configured aggregator");
```
to only load s_proposedAggregator if the sender is _not_ the currentAggregator

2021-05-07 11:38 UTC, kaleofduty commented
Another limitation worth documenting may be that we don't do any `aggregatorRoundId` mangling (unlike AggregatorProxy). So a consumer might get different reports for the same roundId.

2021-05-10 11:08 UTC, kaleofduty commented on evm-contracts/src/v0.8/dev/ValidatorProxy.sol
> +    return "ValidatorProxy 1.0.0";
Let's please leave this as `ValidatorProxy 1.0.0-alpha` until the contract is actually finalized. I want to make sure we don't deploy development versions of the contract with a version suggesting they're the production contract.

2021-05-19 15:33 UTC, samsondav approved these changes

2021-05-19 15:33 UTC, samsondav commented on .prettierignore
> +evm-contracts/cache/**/*
Is this a new one?

2021-05-19 15:33 UTC, samsondav commented on evm-contracts/src/v0.8/dev/ValidatorProxy.sol
> +   * We favour `call` over try-catch to ensure that failures are avoided even if the validator address is incorrectly
❤️  english spelling

2021-05-21 07:59 UTC, kaleofduty requested changes
ready to be merged once the version is updated

2021-05-21 07:59 UTC, kaleofduty commented on evm-contracts/src/v0.8/dev/ValidatorProxy.sol
> +    return "ValidatorProxy 1.0.0-alpha";
Ok, now that we're ready to go, please change this to 
```suggestion
    return "ValidatorProxy 1.0.0";
```

2021-05-21 10:44 UTC, archseer approved these changes

2021-05-21 10:45 UTC, merged