Backfill logs in batches
smartcontractkit/chainlink pull request #4308
Opened 2021-04-29 20:30 UTC by PiotrTrzpil

2021-05-07 14:34 UTC, connorwstein requested changes

2021-05-07 14:34 UTC, connorwstein commented on core/services/log/broadcaster_test.go
> +	mockEth.checFilterLogs = func(fromBlock int64, toBlock int64) {
chec -> check

2021-05-10 09:24 UTC, PiotrTrzpil commented
@spooktheducks I wonder what you think as well

2021-05-13 17:43 UTC, connorwstein approved these changes

2021-05-13 19:40 UTC, merged