Add gas multiplier config option
smartcontractkit/chainlink pull request #4341
Opened 2021-05-03 23:52 UTC by j16r

thinking there needs to be some redesign here because this is real dodge, and this code is really easy to modify without actually making the code work as you'd expect, also think the optimism gas limit is actually broken

2021-05-05 13:08 UTC, samsondav requested changes

2021-05-05 13:08 UTC, samsondav commented on core/services/bulletprooftxmanager/bulletprooftxmanager.go
> +		gasLimit, estimateGasErr := s.EthClient.EstimateGas(context.TODO(), callMsg)
I worry about this context here. Should newAttempt take a context now? If not, perhaps we can at least use `eth.DefaultQueryCtx()`

2021-05-05 13:08 UTC, samsondav commented on core/services/bulletprooftxmanager/bulletprooftxmanager.go
> +		gasLimit, estimateGasErr := s.EthClient.EstimateGas(context.TODO(), callMsg)
I would be interested to see what behaviour we get on Optimism if client enables gas bumping now.

2021-05-05 13:08 UTC, samsondav commented on docs/CHANGELOG.md
> +- Add `ETH_GAS_LIMIT_MULTIPLIER` configuration option, the gas limit is multiplied by this value before transmission. So a value of 1.1 will add 10% to the on chain gas limit when a transaction is su
Does it stack with EthGasLimitDefault? Might want to add a bit more to this doc because its quite confusing

2021-05-05 13:08 UTC, samsondav commented on core/store/orm/config.go
> +func (c Config) EthGasLimitMultiplier() float32 {
Can we have a comment explaining what this does on the function?

2021-05-05 13:13 UTC, samsondav requested changes

2021-05-05 13:13 UTC, samsondav commented on core/services/bulletprooftxmanager/eth_broadcaster_test.go
>  	}
I just realised, I don't think this correctly covers the case. We assume here that the etx got inserted with the correct gas limit, but the gas limit is actually decided at insert time and we don't have logic for that.

Check:

- orm.IdempotentInsertEthTxTaskRun
- core/services/offchainreporting/transmitter.go:39
- core/services/keeper/orm.go:151
- core/services/fluxmonitorv2/orm.go:115

2021-05-05 13:14 UTC, samsondav commented on core/services/bulletprooftxmanager/eth_broadcaster_test.go
>  	}
It's already starting to look like we need a separate system to handle Optimism transactions.

2021-05-05 13:20 UTC, Cashfrepl submitted a review, later dismissed

2021-05-06 00:33 UTC, samsondav requested changes

2021-05-06 00:33 UTC, samsondav commented on core/services/bulletprooftxmanager/eth_broadcaster.go
> +	replacementAttempt, err := newAttempt(context.TODO(), eb.store, etx, bumpedGasPrice)
Can we use the `eth.DefaultQueryCtx` here instead? I'm nervous since I know the websocket can permahang sometimes and this is a critical path.

2021-05-06 15:49 UTC, samsondav submitted a review, later dismissed

2021-05-06 17:21 UTC, samsondav approved these changes

2021-05-06 17:59 UTC, merged