Database backup directory should be configurable
smartcontractkit/chainlink pull request #4435
Opened 2021-05-18 14:38 UTC by PiotrTrzpil

From Peter:

The location where the backups are stored should be a new directory by default (/backup?) and preferable configurable so people can create a volume mount or persistent storage to that directory.

Problem: You don't normally want to mount your chainlink's config directory, and if you do mount it you don't want the backups to include the password files that are normally included in the config directory.

2021-05-19 16:17 UTC, samsondav requested changes

2021-05-19 16:17 UTC, samsondav commented on core/store/orm/config.go
> +// DatabaseBackupDir configures the directory for saving the , if it's to be different from the main on
saving the... ?

2021-05-19 16:21 UTC, PiotrTrzpil commented on core/store/orm/config.go
> +// DatabaseBackupDir configures the directory for saving the , if it's to be different from the main on
fixed - thanks

2021-05-20 16:26 UTC, archseer approved these changes

2021-05-21 23:40 UTC, samsondav approved these changes

2021-05-24 12:08 UTC, merged