added keeper interface for smart contract development
smartcontractkit/chainlink pull request #4444
Opened 2021-05-20 14:27 UTC by PatrickAlphaC

2021-05-25 16:30 UTC, samsondav reviewed
Looks fine to me, but what about the other versions of solidity which we support?

2021-05-26 17:13 UTC, alexroan requested changes
Can you add v0.7 and v0.8 interfaces too please? 

(Please note that we've moved 0.8 solidity files to ./contracts instead of ./evm-contracts as part of an ongoing restructure)

2021-06-03 14:42 UTC, alexroan submitted a review, later dismissed

2021-06-03 14:47 UTC, alexroan requested changes
Looks good, just one more ask.

2021-06-03 14:47 UTC, alexroan commented on evm-contracts/src/v0.8/interfaces/KeeperCompatibleInterface.sol
> +pragma solidity ^0.8.0;
Can you please put this file in the `contracts/` directory instead of `evm-contracts/`?

2021-06-03 15:09 UTC, alexroan approved these changes

2021-06-03 15:09 UTC, merged