Drop support for legacy pipeline
smartcontractkit/chainlink pull request #4718
Opened 2021-07-20 14:40 UTC by samsondav

2021-07-30 08:00 UTC, jkongie requested changes
Looks good. No major issues just some minor naming changes and a few questions.

We should look at updating any var which references jobv2 and change its name to job.

2021-07-30 15:50 UTC, samsondav commented on core/internal/cltest/mocks.go
> +// FIXME: Why bother with this wrapper?
Yes but not in this PR, it's already enormous enough as it stands.

2021-07-30 15:51 UTC, samsondav commented on core/internal/features_test.go
> -func TestIntegration_MultiwordV2(t *testing.T) {
Good catch

2021-07-30 16:13 UTC, samsondav commented on core/services/postgres/queries.go
> -// BulkDeleteRuns removes JobRuns and their related records: TaskRuns and
I don't know :)

2021-07-30 16:14 UTC, samsondav commented on core/store/migrations/0053_remove_legacy_pipeline.go
> +const up53 = `
I'll add a warning and note to take a backup before upgrad

2021-07-30 16:15 UTC, samsondav commented on core/store/migrations/migrate_test.go
🪓

2021-08-04 05:09 UTC, jkongie submitted a review, later dismissed

2021-08-04 13:35 UTC, archseer approved these changes

2021-08-04 13:36 UTC, PiotrTrzpil approved these changes

2021-08-04 13:40 UTC, jkongie approved these changes

2021-08-04 13:49 UTC, merged