[WIP] chore/ch10934 Use pipeline for VRF tasks
smartcontractkit/chainlink pull request #4729
Opened 2021-07-22 22:35 UTC by connorwstein

2021-07-26 17:26 UTC, connorwstein commented on core/services/job/orm.go
> +func (o *orm) FindJobTx(id int32) (Job, error) {
There are a few top level endpoints which just want to lookup a job and don't have a TxManager nor direct access to a db to create one.

2021-07-26 17:27 UTC, samsondav requested changes
Where is the example for the new VRF toml spec?

2021-07-26 17:29 UTC, connorwstein commented
> Where is the example for the new VRF toml spec?

https://github.com/smartcontractkit/chainlink/pull/4729/files#diff-a39f1402fa0a50324d3c640634ee7425c82936366887cd77f7ae17cef9bcd7b5

2021-07-26 17:34 UTC, samsondav approved these changes

2021-07-26 18:11 UTC, connorwstein commented on core/web/presenters/pipeline_run.go
> +			case map[string]interface{}:
This is the main reason for the presenter - to be able to take a map task output and convert to a string. @jkongie you may have opinions on this

2021-07-27 09:30 UTC, samsondav approved these changes

2021-07-27 14:48 UTC, merged