Remove angle bracket attributes before FE parsing
smartcontractkit/chainlink pull request #4894
Opened 2021-08-24 14:29 UTC by connorwstein

See comment in code. UI example:
![image](https://user-images.githubusercontent.com/5782319/130635169-3814e3b8-1ccc-4ffa-963e-aa3a38ffa301.png)
![image](https://user-images.githubusercontent.com/5782319/130635197-9d45a044-3146-45f0-8a8a-8982b82791d2.png)

2021-08-24 16:07 UTC, jkongie requested changes

2021-08-24 16:07 UTC, jkongie commented on operator_ui/src/pages/Jobs/parseDot.ts
> +  const dotNoAngleBrackets = dot.replace(/\w+=<.*>/g, '')
```suggestion
  const dotNoAngleBrackets = dot.replace(/\w+\s*=\s*<.*>/g, '')
```

This should handle spacing between the key, equal sign and value.

For example
```
bla1231h = <"">
```

2021-08-24 20:23 UTC, jkongie submitted a review, later dismissed

2021-08-25 00:32 UTC, archseer approved these changes

2021-08-25 02:56 UTC, merged