Remove gorm from cltest/job_factories
smartcontractkit/chainlink pull request #5416
Opened 2021-11-11 15:11 UTC by RensR

2021-11-11 15:47 UTC, samsondav requested changes

2021-11-11 15:47 UTC, samsondav commented on core/internal/cltest/job_factories.go
> +	webhookSpecID, err := jobORM.InsertWebhookSpec(&webhookSpec)
It might be preferable to rewrite `InsertWebhookSpec` so that instead of returning the id it uses `RETURNING *` to scan into the passed pointer.

2021-11-11 15:47 UTC, samsondav commented on core/internal/cltest/job_factories.go
> +	jobID, err := jobORM.InsertJob(&job)
Same here as for `InsertWebhookSpec`

2021-11-11 15:47 UTC, samsondav commented on core/services/job/job_orm_test.go
> +		gdb2 := pgtest.NewGormDB(t)
Can we get rid of gorm entirely from this test file?

2021-11-11 15:47 UTC, samsondav commented on core/services/job/orm.go
> +	err = postgres.PrepareQueryRowx(q, query, &jobId, jobSpec)
Prefer to use q.Get

2021-11-11 15:47 UTC, samsondav commented on core/services/job/orm.go
> +	err = postgres.PrepareQueryRowx(q, query, &specID, webhookSpec)
Prefer to use q.Get

2021-11-11 15:47 UTC, samsondav commented on core/services/job/orm.go
> +	// Take the largest of the global vs specific.
That wasn't a typo, its actually correct to use "larger" when comparing only two objects

2021-11-11 15:47 UTC, samsondav commented on core/services/job/orm.go
> +// PipelineRuns returns pipeline runs for a job, with spec and taskruns loaded, the latest first
reads better as before imo

2021-11-12 10:42 UTC, pinebit approved these changes

2021-11-12 10:42 UTC, pinebit commented on core/internal/cltest/job_factories.go
> +	"github.com/smartcontractkit/sqlx"
AFAIK we should be sorting imports so that all smartcontractkit/* are grouped in one section

2021-11-12 14:07 UTC, pinebit approved these changes

2021-11-12 14:48 UTC, pinebit commented
@cl-home r+

2021-11-12 14:48 UTC, pinebit commented
@cl-homu r+

2021-11-12 14:48 UTC, cl-homu commented
:pushpin: Commit 22c89ae7fe4dd673c0bd4ac4537780ffede34ece has been approved by `pinebit`

<!-- @cl-homu r=pinebit 22c89ae7fe4dd673c0bd4ac4537780ffede34ece -->
<!-- homu: {"type":"Approved","sha":"22c89ae7fe4dd673c0bd4ac4537780ffede34ece","approver":"pinebit"} -->

2021-11-12 14:49 UTC, cl-homu commented
:hourglass: Testing commit 22c89ae7fe4dd673c0bd4ac4537780ffede34ece with merge 37818613696fe405dd705ab52a5cf3e753df0789...
<!-- homu: {"type":"BuildStarted","head_sha":"22c89ae7fe4dd673c0bd4ac4537780ffede34ece","merge_sha":"37818613696fe405dd705ab52a5cf3e753df0789"} -->

2021-11-12 14:58 UTC, cl-homu commented
:sunny: Test successful - [checks-core](https://github.com/smartcontractkit/chainlink/runs/4191031912?check_suite_focus=true), [checks-lint](https://github.com/smartcontractkit/chainlink/runs/4191032050?check_suite_focus=true), [checks-npm](https://github.com/smartcontractkit/chainlink/runs/4191032063?check_suite_focus=true), [checks-operator](https://github.com/smartcontractkit/chainlink/runs/4191032021?check_suite_focus=true), [checks-prettier](https://github.com/smartcontractkit/chainlink/runs/4191031867?check_suite_focus=true), [checks-solidity](https://github.com/smartcontractkit/chainlink/runs/4191031877?check_suite_focus=true)
Approved by: pinebit
Pushing 37818613696fe405dd705ab52a5cf3e753df0789 to develop...
<!-- homu: {"type":"BuildCompleted","approved_by":"pinebit","base_ref":"develop","builders":{"checks-core":"https://github.com/smartcontractkit/chainlink/runs/4191031912?check_suite_focus=true","checks-operator":"https://github.com/smartcontractkit/chainlink/runs/4191032021?check_suite_focus=true","checks-lint":"https://github.com/smartcontractkit/chainlink/runs/4191032050?check_suite_focus=true","checks-npm":"https://github.com/smartcontractkit/chainlink/runs/4191032063?check_suite_focus=true","checks-prettier":"https://github.com/smartcontractkit/chainlink/runs/4191031867?check_suite_focus=true","checks-solidity":"https://github.com/smartcontractkit/chainlink/runs/4191031877?check_suite_focus=true"},"merge_sha":"37818613696fe405dd705ab52a5cf3e753df0789"} -->

2021-11-12 14:58 UTC, merged