remove gorm implementation
smartcontractkit/chainlink pull request #5852
Opened 2022-01-25 17:37 UTC by MStreet3

### [27354: remove gorm implementation](https://app.shortcut.com/chainlinklabs/story/27354/remove-gorm-methods-like-tablename)

`gorm` had a `Tabler` interface ([docs](https://gorm.io/docs/conventions.html#TableName)) which required the `TableName` method be implemented.

this PR removes implementation of the `Tabler` interface.

2022-01-25 18:46 UTC, prashantkumar1982 requested changes
Overall looks good. But please check the test failure.
Once that is fixed, I can approve.

2022-01-25 18:48 UTC, vyzaldysanchez reviewed
I've started a run for the tests again since looks like the OCR2 test flake was triggered here. Once I see this passing, I will approve.

2022-01-25 18:51 UTC, jmank88 approved these changes

2022-01-25 18:54 UTC, vyzaldysanchez approved these changes

2022-01-26 18:22 UTC, prashantkumar1982 approved these changes

2022-01-26 18:22 UTC, merged