core/chains/terra/terratxm: limit terra_msgs queries
smartcontractkit/chainlink pull request #6016
Opened 2022-02-15 21:03 UTC by jmank88

https://app.shortcut.com/chainlinklabs/story/29943

2022-02-15 23:45 UTC, RyanRHall approved these changes

2022-02-15 23:45 UTC, RyanRHall commented on core/chains/terra/terratxm/txm.go
> +				txm.lggr.Errorw("unable to parse sender", "err", err, "sender", ms.Sender)
maybe `Criticalw`, for consistency

2022-02-16 16:00 UTC, connorwstein requested changes

2022-02-16 17:24 UTC, jmank88 commented on core/chains/terra/terratxm/txm.go
> +	for {
Yeah I overlooked the slice with MaxMsgsPerBatch initially :+1:

2022-02-16 18:09 UTC, jmank88 commented
Hmmmm I wonder if that smoke test failure is 'real' from expecting messages faster than we send now...

2022-02-16 18:22 UTC, jmank88 commented
> Hmmmm I wonder if that smoke test failure is 'real' from expecting messages faster than we send now...

nvm, pre-existing

2022-02-16 22:24 UTC, merged