Fix flakey tests which do login via CLI
smartcontractkit/chainlink pull request #6254
Opened 2022-03-18 15:22 UTC by infiloop2

Fixing more failing tests from https://github.com/smartcontractkit/chainlink/pull/6123 

Not sure why they are being flakey though

2022-03-18 15:29 UTC, samsondav approved these changes

2022-03-18 15:33 UTC, jmank88 approved these changes

2022-03-18 15:35 UTC, samsondav requested changes

2022-03-18 15:35 UTC, samsondav commented on core/cmd/eth_keys_commands_test.go
>  	set.String("file", "internal/fixtures/apicredentials", "")
This file should be unique per test

2022-03-21 11:46 UTC, infiloop2 commented
Fixed in https://github.com/smartcontractkit/chainlink/pull/6263

2022-03-21 11:46 UTC, closed without merging