Feature keeper registry 1.2.0
smartcontractkit/chainlink pull request #6348
Opened 2022-03-31 21:33 UTC by RyanRHall

2022-04-01 04:46 UTC, se3000 requested changes

2022-04-01 04:46 UTC, se3000 commented on contracts/src/v0.7/dev/KeeperRegistryDev.sol
> +  function ownerWithdrawFunds() external onlyOwner {
```suggestion
  function withdrawOwnerFunds() external onlyOwner {
```
Naming nit-pick. From the styleguide:
> Function names should start with imperative verbs, not nouns or other tenses.

2022-04-01 10:05 UTC, infiloop2 commented on contracts/src/v0.7/dev/KeeperRegistryDev.sol
> +  function ownerWithdrawFunds() external onlyOwner {
fixed

2022-04-02 02:22 UTC, RyanRHall commented
@se3000 @infiloop2 I'd like to get https://github.com/smartcontractkit/chainlink/pull/6370 merged before making further changes.

2022-04-04 10:52 UTC, infiloop2 commented on contracts/src/v0.8/dev/KeeperRegistryDev.sol
> +      if (upkeep.admin != admin) revert OnlyCallableByAdmin();
The error name is confusing for readability.

2022-04-21 14:47 UTC, infiloop2 commented
Closing in favor of https://github.com/smartcontractkit/chainlink/pull/6479

2022-04-21 14:47 UTC, closed without merging