Remove service level logging
smartcontractkit/chainlink pull request #6616
Opened 2022-05-13 16:21 UTC by samsondav

2022-05-13 18:01 UTC, jmank88 commented on .tool-versions
> +mockery 2.12.2
`GNUmakefile` too?

2022-05-16 02:41 UTC, vyzaldysanchez requested changes

2022-05-16 02:41 UTC, vyzaldysanchez commented on core/web/resolver/mutation.go
> -	return NewSetServicesLogLevelsPayload(&args.Input.Config, nil), nil
We can also remove the definition of this constructor and the struct related to it, since it won't be used anymore.

2022-05-16 02:41 UTC, vyzaldysanchez commented on core/web/resolver/mutation.go
> -	return NewSetServicesLogLevelsPayload(&args.Input.Config, nil), nil
File related is here: https://github.com/smartcontractkit/chainlink/blob/e4cc231949af3fc5290cea5ebd6c101759791676/core/web/resolver/log.go#L81

2022-05-16 14:25 UTC, jmank88 submitted a review, later dismissed

2022-05-16 14:57 UTC, vyzaldysanchez requested changes
I don't think we need to fully remove `core/web/resolver/log_test.go`, since there's still functionality being tested in that file not related to the service level logging. Like SQL Logging and Global log level.

2022-05-16 15:07 UTC, pinebit approved these changes

2022-05-16 15:45 UTC, jmank88 approved these changes

2022-05-16 15:46 UTC, merged