feat (vrf v2 mock): user provided words
smartcontractkit/chainlink pull request #6653
Opened 2022-05-20 17:13 UTC by cuckflong

implementation to #6652

2022-05-25 07:56 UTC, cuckflong commented
> Good change! However, some users use this mock file in their existing tests, so this change would break those tests.
> 
> It's best to use overloading:
> 
> ```
> fulfillRandomWords(uint256 _requestId, address _consumer) external {
>   fulfillRandomWords(_requestId, _consumer, new uint256[](0));
> }
> 
> fulfillRandomWords(uint256 _requestId, address _consumer, uint256[] memory _words) external {
>   ...
> }
> ```

Great suggestion! Have updated the code to use overloading

2022-05-26 14:05 UTC, cuckflong commented
has updated accordingly

2022-05-26 15:39 UTC, vreff approved these changes

2022-05-26 16:27 UTC, vreff commented
Try running this locally:
```
yarn workspace @chainlink/contracts hardhat test
```

2022-05-26 16:48 UTC, cuckflong commented
<img width="960" alt="CleanShot 2022-05-27 at 00 47 43@2x" src="https://user-images.githubusercontent.com/28383100/170535491-ad93ef8e-7ac1-43da-b38f-909159829e46.png">

getting the above errors

2022-05-27 00:12 UTC, vreff requested changes
Oops this is my bad! It looks like hardhat tests run into issues if you overload and call a function. So, to get around that without changing any tests we can just rename the 3 parameter function to `fulfillRandomWordsWithOverride`, so that we're no longer truly overloading and the tests are intact. You should be able to just commit the suggestions I've added, and I'll re-run the tests.

2022-05-27 00:12 UTC, vreff commented on contracts/src/v0.8/mocks/VRFCoordinatorV2Mock.sol
> +  function fulfillRandomWords(
```suggestion
  function fulfillRandomWordsWithOverride(
```

2022-05-27 00:12 UTC, vreff commented on contracts/src/v0.8/mocks/VRFCoordinatorV2Mock.sol
> +    fulfillRandomWords(_requestId, _consumer, new uint256[](0));
```suggestion
    fulfillRandomWordsWithOverride(_requestId, _consumer, new uint256[](0));
```

2022-05-27 00:12 UTC, vreff commented on contracts/test/v0.8/dev/VRFCoordinatorV2Mock.test.ts
> +          ['fulfillRandomWords(uint256,address)'](1, vrfConsumerV2.address),
```suggestion
          .fulfillRandomWords(1, vrfConsumerV2.address),
```

2022-05-27 00:12 UTC, vreff commented on contracts/test/v0.8/dev/VRFCoordinatorV2Mock.test.ts
> +        ['fulfillRandomWords(uint256,address)'](1, vrfConsumerV2.address)
```suggestion
        .fulfillRandomWords(1, vrfConsumerV2.address)
```

2022-05-27 00:16 UTC, vreff commented on contracts/src/v0.8/mocks/VRFCoordinatorV2Mock.sol
> +   */
```suggestion
```

2022-05-27 01:28 UTC, vreff approved these changes

2022-05-27 02:57 UTC, cuckflong commented
great thanks!

2022-05-31 16:42 UTC, vreff commented
Moving to https://github.com/smartcontractkit/chainlink/pull/6697, so all checks will pass.

2022-05-31 16:42 UTC, closed without merging