tools/bin: remove p/parallel flags from tests
smartcontractkit/chainlink pull request #6856
Opened 2022-06-24 04:03 UTC by jmank88

2022-06-24 14:14 UTC, pinebit submitted a review, later dismissed

2022-06-24 18:05 UTC, vyzaldysanchez submitted a review, later dismissed

2022-06-24 22:10 UTC, jmank88 commented
Hmmmm the Solana integration tests from different packages are clashing with one another...
They already use random ports though. Investigating..

2022-06-27 12:29 UTC, jmank88 commented on core/chains/solana/soltxm/txm_test.go
> +	ctx, cancel := context.WithCancel(ctx)
:crossed_fingers: This may be enough to relieve the pressure - the test was quitting at 30s but the package has 2m.

2022-06-27 14:39 UTC, vyzaldysanchez requested changes
Tests are failing as result of these changes?

2022-06-27 19:58 UTC, jmank88 commented
> Tests are failing as result of these changes?

Yeah, two separate solana integration tests from different packages are conflicting when we let more packages run concurrently. I don't see exactly why though - need to look closer.

cc @aalu1418

2022-06-28 20:45 UTC, vyzaldysanchez submitted a review, later dismissed

2022-06-28 21:28 UTC, jmank88 commented
Huh, it passed once finally. Well that is consistent with the theory.

2022-07-18 14:44 UTC, jmank88 commented
Three successful runs in a row now, after rebasing a few hours ago. :shrug:

2022-07-18 19:24 UTC, jmank88 commented
6 or 7 successful in a row, but now the old error again... :cry: 

cc @aalu1418

2022-08-04 18:18 UTC, essamhassan approved these changes
LGTM

2022-08-04 19:34 UTC, jmank88 commented
I'm not sure if this has stabilized or could fail again, but I'm going to merge and we can circle back on the root cause solana test if it comes up again.

2022-08-04 19:35 UTC, merged