Send gas value as part of `eth_call`
smartcontractkit/chainlink pull request #7059
Opened 2022-07-22 21:20 UTC by vyzaldysanchez

2022-07-26 15:20 UTC, samsondav approved these changes

2022-07-26 15:21 UTC, samsondav requested changes
Can we have details in the commit message explaining why this is necessary?

2022-07-26 15:52 UTC, vyzaldysanchez commented
This might no longer be necessary, waiting on confirmation from GetBlock and QA.

2022-08-04 18:19 UTC, closed without merging

2022-08-04 18:20 UTC, vyzaldysanchez commented
Closed since we do not need this!