Bump integration versions
smartcontractkit/chainlink pull request #7513
Opened 2022-09-23 02:11 UTC by reductionista

2022-09-23 16:40 UTC, jmank88 commented on go.mod
> +)
These escaped!

2022-09-26 16:58 UTC, tateexon requested changes

2022-09-26 16:58 UTC, tateexon commented on integration-tests/go.mod
> +	github.com/smartcontractkit/chainlink-testing-framework v1.6.5
Looks like you moved us back a version of the testing framework

2022-09-26 18:32 UTC, reductionista commented
I think this is ready now.  I've opened sister PR's for `chainlink-env` and `chainlink-testing-framework`, once all 3 of these have been merged then all of them will be in sync at golang version 1.19.1:
https://github.com/smartcontractkit/chainlink-env/pull/168
https://github.com/smartcontractkit/chainlink-testing-framework/pull/447

Re-review @jmank88 @tateexon ?

2022-09-26 19:00 UTC, tateexon approved these changes

2022-09-27 11:21 UTC, jmank88 approved these changes

2022-09-28 05:10 UTC, vyzaldysanchez approved these changes

2022-09-28 06:44 UTC, jmank88 approved these changes

2022-09-28 07:09 UTC, merged