Update Benchmark Test - test compilation changes
smartcontractkit/chainlink pull request #7747
Opened 2022-10-25 07:55 UTC by anirudhwarrier

2022-10-25 13:31 UTC, kalverra requested changes

2022-10-25 13:31 UTC, kalverra commented on integration-tests/actions/keeper_benchmark_helpers.go
> +	contractLoader, _ := contracts.NewContractLoader(client)
Why ignore this error?

2022-10-25 13:31 UTC, kalverra commented on integration-tests/actions/keeper_benchmark_helpers.go
> +	upkeepResetter, _ := contractLoader.LoadUpkeepResetter(common.HexToAddress(upkeepResetterAddr))
And this one?

2022-11-02 15:24 UTC, infiloop2 approved these changes

2022-11-02 17:39 UTC, merged