OCR2DR - Admin killswitch
smartcontractkit/chainlink pull request #8121
Opened 2022-12-12 16:38 UTC by justinkaseman

2022-12-13 02:28 UTC, bolekk reviewed
I'm a little confused by this PR - it seems to contain several unrelated changes. Is it still a draft or ready to review?

2022-12-13 02:28 UTC, bolekk commented on contracts/src/v0.8/dev/ocr2dr/OCR2DRRegistry.sol
> +  function timeoutRequests(uint64 subscriptionId) external onlySubOwner(subscriptionId) onlyActiveRegistry {
Why is this part of this PR?

2022-12-14 17:23 UTC, justinkaseman commented
> I think we need to consider implementing this https://github.com/OpenZeppelin/openzeppelin-contracts/blob/master/contracts/security/Pausable.sol

That sounds good to me, I'll implement

2022-12-14 23:03 UTC, KuphJr requested changes
Where is the external function allowing the owner to `pause` and `unpause`? I only see the internal functions `_pause()` and `_unpause`?

2022-12-14 23:04 UTC, justinkaseman commented
> Where is the external function allowing the owner to `pause` and `unpause`? I only see the internal functions `_pause()` and `_unpause`?

https://github.com/smartcontractkit/chainlink/pull/8121/files#diff-27f1b21cbbc1c90bc638ee9175f21a0bab8f511c5544b261dbe76c0e57b47553R89

2022-12-14 23:24 UTC, KuphJr submitted a review, later dismissed

2022-12-15 02:01 UTC, bolekk submitted a review, later dismissed
lgtm

2022-12-15 02:25 UTC, KuphJr approved these changes

2022-12-15 13:31 UTC, pinebit approved these changes

2022-12-15 17:42 UTC, bolekk approved these changes

2022-12-15 17:43 UTC, merged