Use paths action for filtering jobs instead of separate ignore workflows
smartcontractkit/chainlink pull request #8187
Opened 2023-01-03 23:04 UTC by chainchad

2023-01-03 23:06 UTC, chainchad commented
This is what we do for the integration-tests.yml and solidity*.yml workflows.

2023-01-03 23:33 UTC, HenryNguyen5 requested changes

2023-01-03 23:33 UTC, HenryNguyen5 commented on .github/workflows/golangci-lint.yml
> +          (needs.changes.outputs.src == 'true' && (github.event_name == 'push' || (github.event_name == 'pull_request' && !startsWith(github.head_ref, 'release/')))
```suggestion
          (needs.changes.outputs.src == 'true' && (github.event_name == 'push' || github.event_name == 'pull_request' )
```

2023-01-03 23:33 UTC, HenryNguyen5 commented on .github/workflows/golangci-lint.yml
>    pull_request:
Could we do this instead?

2023-01-04 13:15 UTC, jmank88 submitted a review, later dismissed

2023-01-04 13:18 UTC, chainchad commented on .github/workflows/golangci-lint.yml
>    pull_request:
Good idea. There was a formatting issue in this suggestion so I made the change in 045f78bf317b8c6c78c3d594b64863b55146089a.

2023-01-04 13:22 UTC, jmank88 approved these changes

2023-01-04 13:25 UTC, chainchad commented on .github/workflows/golangci-lint.yml
> +          (needs.changes.outputs.src == 'true' && (github.event_name == 'push' || (github.event_name == 'pull_request' && !startsWith(github.head_ref, 'release/')))
This simplifies things nicely

2023-01-04 20:41 UTC, HenryNguyen5 submitted a review, later dismissed

2023-01-04 21:59 UTC, jmank88 approved these changes

2023-01-04 22:05 UTC, merged