Arbitrum blocknum keeper registry
smartcontractkit/chainlink pull request #8399
Opened 2023-02-08 19:32 UTC by RyanRHall

2023-02-09 21:04 UTC, infiloop2 commented on contracts/src/v0.8/keeper2_0/KeeperRegistryBase2_0.sol
> +  Mode internal immutable s_mode;
i_mode since it's immutable

2023-02-09 21:18 UTC, infiloop2 requested changes
Looks good! Like the clean solution even though at expense of some extra gas.

Just one comment about variable name to align with solidity guidelines

2023-02-10 14:58 UTC, RyanRHall commented on contracts/src/v0.8/keeper2_0/KeeperRegistryBase2_0.sol
> +  Mode internal immutable s_mode;
fixed!

2023-02-10 15:01 UTC, infiloop2 approved these changes

2023-02-10 15:02 UTC, merged