Add pre-install script to run pnpm clean
smartcontractkit/chainlink pull request #8940
Opened 2023-04-10 18:21 UTC by justinkaseman

2023-04-11 00:34 UTC, jmank88 submitted a review, later dismissed

2023-04-11 16:47 UTC, samsondav submitted a review, later dismissed

2023-04-11 17:16 UTC, justinkaseman commented
Waiting on Release Engineering team's feedback before merging

2023-04-12 17:41 UTC, HenryNguyen5 requested changes
I don't think this is how we want to accomplish clean installs. Per the `pnpm` documentation:
```
Do not execute any scripts defined in the project package.json and its **dependencies**.
```

This is going to possibly change project behaviour during prod since we'll be skipping dep lifecycle scripts too, not just our own.

I've opened up https://github.com/OpenZeppelin/openzeppelin-upgrades/pull/769 to allow for configurable retries, which should solve the crux of the issue which is high lockfile contention causing timeouts

2023-04-12 17:41 UTC, HenryNguyen5 commented on .github/actions/setup-nodejs/action.yaml
> +      run: pnpm i --prod --ignore-scripts true
```suggestion
      run: pnpm i --prod --ignore-scripts
```

Don't think we need the boolean here

2023-04-12 18:43 UTC, justinkaseman commented
Closing in favor of hardhat-upgrades PR

2023-04-12 18:43 UTC, closed without merging