Merc-478: Current block timestamp to Mercury report
smartcontractkit/chainlink pull request #9091
Opened 2023-05-01 13:38 UTC by sdrug

2023-05-01 17:22 UTC, samsondav requested changes
[Needs](https://github.com/smartcontractkit/chainlink-relay/pull/107)

2023-05-05 21:09 UTC, samsondav approved these changes

2023-05-05 21:09 UTC, samsondav commented on core/services/relay/evm/mercury/data_source.go
> +	if latestHead.Timestamp.IsZero() {
This case should be impossible

2023-05-05 22:25 UTC, jmank88 approved these changes

2023-05-05 22:52 UTC, merged