[Gateway] HTTP server
smartcontractkit/chainlink pull request #9220
Opened 2023-05-12 20:56 UTC by bolekk

Adding
1. HTTP server for user requests.
2. ProcessRequest function that decodes the request, calls a handler and encodes the response.
3. Script to run Gateway outside of the core node, for testing purposes.

2023-05-16 06:04 UTC, pinebit requested changes
Provided my comments.

2023-05-16 06:04 UTC, pinebit commented on core/services/gateway/network/httpserver.go
> +	SetHTTPRequestHandler(handler HTTPRequestHandler)
Have a comment: not thread-safe.

2023-05-16 06:04 UTC, pinebit commented on core/services/gateway/network/httpserver.go
> +	done    chan bool
Core naming pattern is `xyzCh` (Ch suffix) for any channel.

2023-05-16 06:04 UTC, pinebit commented on core/services/gateway/handler.go
> +	HandleUserMessage(ctx context.Context, msg *Message, callbackChan chan<- UserCallbackPayload) error
Core naming pattern is `xyzCh` (Ch suffix) for any channel.

2023-05-16 20:10 UTC, bolekk commented on core/services/gateway/network/httpserver.go
> +	ReadTimeoutMillis    uint32
It looks like I would need to use the Duration struct from core/store/models.go or implement something similar myslef. I'm not too keen on adding another core dependency so I'll leave it for now.

2023-05-17 05:52 UTC, pinebit approved these changes

2023-05-17 15:25 UTC, merged