Functions: S4 in-memory storage
smartcontractkit/chainlink pull request #9262
Opened 2023-05-18 07:56 UTC by pinebit

2023-05-19 01:01 UTC, bolekk requested changes

2023-05-19 08:35 UTC, pinebit commented on core/services/s4/envelope.go
> +// Hex is not used to avoid confusion due to case-sensivity and 0x prefix.
That json is not meant to be read. It is temporary constructed in runtime for both client and server and should not even appear in logs.

2023-05-19 08:43 UTC, pinebit commented on core/services/s4/storage.go
> +	Confirmed         bool
Initially I did that. But then I realized that "EXPIRED" can easily be deducted from `Expiration < now()`. Also, changing records state to EXPIRED would require additional write operations on DB, whereas a simply query `where expiration < now()` would do the trick.
Maybe I will revisit this when working on the plugin. But for now, the simpler the better.

2023-05-19 08:43 UTC, pinebit commented on core/services/s4/storage.go
> +type RecordState int
A leftover, removed.

2023-05-19 09:09 UTC, pinebit commented on core/services/s4/envelope.go
> +	js, err := json.Marshal(e)
The current implementation (standard) of `JSON.stringify` and `json.Marshal` respect declaration order and do not insert any whitespace unless requested by the user. If there is a system that has a different behavior, then it needs to implement custom json serialization. I

2023-05-19 09:22 UTC, pinebit commented on core/services/s4/storage.go
> +		}
The new record expiration can be larger than the previously recorded highest expiration, right?
I feel we have misunderstanding on the purpose of highest expiration term.
I think this "highest expiration" complicates the things, I will get back to the CLIP to find a better idea.

2023-05-19 09:46 UTC, pinebit commented on core/services/s4/orm.go
> +type Entry struct {
Fixed

2023-05-19 11:37 UTC, pinebit commented on core/services/s4/envelope.go
> +func (e Envelope) Sign(privateKey *ecdsa.PrivateKey) (signature []byte, err error) {
See my PM. I think we need to get rid of HighestExpiration at all and make GC mandatory. NOPs shall not take risks while persisting any user records for a long time. They only need to guarantee persistence until Expiration deadline.

2023-05-22 06:31 UTC, pinebit commented on core/services/s4/envelope.go
> +func (e Envelope) Sign(privateKey *ecdsa.PrivateKey) (signature []byte, err error) {
UPD: removed HighestExpiration. The user queries data by address/slot/version.

2023-05-23 04:00 UTC, bolekk approved these changes
LGTM

2023-05-23 04:00 UTC, bolekk commented on core/services/s4/envelope.go
> +	js := fmt.Sprintf(`{"address":%s,"slotid":%d,"payload":%s,"version":%d,"expiration":%d}`, address, e.SlotID, payload, e.Version, e.Expiration)
Hopefully we can silence those by some clever string concatenation...?

2023-05-23 05:15 UTC, pinebit commented on core/services/s4/storage.go
> +type Metadata struct {
`Storage` interface is not meant to be used by OCR plugin, it is a public "user" interface. OCR plugin will use ORM.

2023-05-23 05:15 UTC, pinebit commented on core/services/s4/storage.go
> +	if row != nil && key.Version <= row.Version {
`Storage` interface is not meant to be used by OCR plugin, it is a public "user" interface. OCR plugin will use ORM.

2023-05-23 05:16 UTC, pinebit commented on core/services/s4/orm.go
> +	// DeleteExpired deletes any entries having HighestExpiration < now().
Good catch, will fix it in the next PR

2023-05-23 05:31 UTC, pinebit commented
Merging to proceed with OCR plugin, I will address the remaining minor comments in the next PR.

2023-05-23 05:31 UTC, merged