Adds Scroll network to list of known networks
smartcontractkit/chainlink pull request #9299
Opened 2023-05-22 10:51 UTC by mohamed-mehany

2023-05-23 13:38 UTC, samsondav requested changes

2023-05-23 13:38 UTC, samsondav commented on core/chains/evm/config/v2/defaults/Scroll_Testnet.toml
> +# Never bump gas on optimism
bad copypasta

2023-05-23 13:55 UTC, mohamed-mehany commented on core/chains/evm/config/v2/defaults/Scroll_Testnet.toml
> +# Never bump gas on optimism
Good catch! Thanks @samsondav

2023-08-01 07:33 UTC, tonynguyen-ccl submitted a review, later dismissed

2023-10-12 00:10 UTC, closed without merging