Offchain secrets fetching func
smartcontractkit/chainlink pull request #9369
Opened 2023-05-26 22:07 UTC by KuphJr

2023-05-30 05:32 UTC, pinebit requested changes
A few improvements suggested

2023-05-30 05:32 UTC, pinebit commented on core/services/functions/external_adapter_client.go
> +	AdapterURL string
This should be of type `url.Url` https://pkg.go.dev/net/url#example-URL

2023-05-30 05:32 UTC, pinebit commented on core/services/functions/external_adapter_client.go
> +	req, err := http.NewRequest("POST", ea.AdapterURL+"/fetcher", bytes.NewBuffer(jsonPayload))
https://pkg.go.dev/net/url#URL.JoinPath

2023-05-30 05:32 UTC, pinebit commented on core/services/functions/external_adapter_client.go
> +func (ea ExternalAdapterInterface) FetchEncryptedSecrets(encryptedSecretsUrls []byte, requestId string, jobName string) (encryptedSecrets, userError []byte, err error) {
IO functions should have the first argument of type `context.Context`

2023-05-30 05:32 UTC, pinebit commented on core/services/functions/external_adapter_client.go
> +	req, err := http.NewRequest("POST", ea.AdapterURL+"/fetcher", bytes.NewBuffer(jsonPayload))
https://pkg.go.dev/net/http#NewRequestWithContext

2023-05-30 05:32 UTC, pinebit commented on core/services/functions/external_adapter_client.go
> +		userError, err = hex.DecodeString(apiResponse.Data.Error[2:])
Please use `utils.TryParseHex`

2023-05-30 05:32 UTC, pinebit commented on core/services/functions/external_adapter_client.go
> +		userError, err = hex.DecodeString(apiResponse.Data.Error[2:])
`apiResponse.Data` can be `nil` and this will panic, if the `Response` body has missing `Data`

2023-05-31 04:40 UTC, bolekk requested changes

2023-05-31 04:40 UTC, bolekk commented on core/services/functions/external_adapter_client.go
> +func (ea ExternalAdapterInterface) FetchEncryptedSecrets(ctx context.Context, encryptedSecretsUrls []byte, requestId string, jobName string) (encryptedSecrets, userError []byte, err error) {
It looks like the only thing specific to secrets is the Payload struct. Can we convert most of this method into a generic request method and only have a small specialized one for secrets on top of it?
We will likely reuse the generic one for the other bridge soon.

2023-05-31 04:40 UTC, bolekk commented on core/services/functions/external_adapter_client.go
> +	req, err := http.NewRequestWithContext(ctx, "POST", ea.AdapterURL.JoinPath("/fetcher").String(), bytes.NewBuffer(jsonPayload))
Can we require that the "/fetcher" path is just part of the URL and needs to be set by the caller?

2023-05-31 04:40 UTC, bolekk commented on core/services/functions/external_adapter_client.go
> +	body, err := io.ReadAll(resp.Body)
We should support at least a size limit. See : https://github.com/smartcontractkit/chainlink/blob/develop/core/utils/http/http.go#L70

Timeouts are hopefully supported by the context.

2023-05-31 05:09 UTC, pinebit submitted a review, later dismissed
From my end all good. Review Bolek's comments.

2023-05-31 22:02 UTC, bolekk requested changes

2023-05-31 22:02 UTC, bolekk commented on core/services/functions/external_adapter_client_test.go
> +func Test_FetchEncryptedSecrets_Success(t *testing.T) {
Can you convert every test into a single helper function call along the lines of "runTest(adapterJSONResponse, expectedSecrets, expectedUserError, expectedError)"?

2023-05-31 22:05 UTC, KuphJr commented on core/services/functions/external_adapter_client.go
> +		Endpoint:  "fetcher",
Yeah.  Turns out the EA framework supports "endpoints" as params in the payload, not URL endpoints. If the endpoint param is not specified, it defaults to lambda.

2023-05-31 23:36 UTC, bolekk approved these changes

2023-05-31 23:36 UTC, bolekk commented on core/services/functions/external_adapter_client.go
> +) (userResult, userError []byte, err error) {
my bad, I forgot that []byte applies to both but I'm surprised linter isn't complaining

2023-05-31 23:36 UTC, merged