add support for allowlist
smartcontractkit/chainlink pull request #9379
Opened 2023-05-30 20:00 UTC by FelixFan1992

2023-05-30 20:27 UTC, RyanRHall commented on contracts/src/v0.8/dev/automation/2_1/KeeperRegistryLogicB2_1.sol
> +    s_upkeepAdminOffchainConfig[upkeepId] = newAdminOffchainConfig;
I think we will want to emit an event here

2023-05-30 20:29 UTC, RyanRHall requested changes

2023-05-30 20:29 UTC, RyanRHall commented on contracts/src/v0.8/dev/automation/2_1/KeeperRegistryLogicB2_1.sol
> +  }
I think we will want to emit an event here

2023-05-30 20:55 UTC, RyanRHall approved these changes

2023-05-30 21:08 UTC, merged

2023-06-06 10:54 UTC, infiloop2 commented on contracts/src/v0.8/dev/automation/2_1/KeeperRegistryLogicB2_1.sol
> +  function setUpkeepManager(address newUpkeepManager) external onlyOwner {
can we combine this within setConfig? One place to set all owner config

2023-06-06 10:55 UTC, infiloop2 commented on contracts/src/v0.8/dev/automation/2_1/KeeperRegistryBase2_1.sol
> +    s_upkeepManager = msg.sender;
not sure if we really need to set this here. This can be set during setConfig, while only immutables are needed during construction time

2023-06-06 10:55 UTC, infiloop2 commented on contracts/src/v0.8/dev/automation/2_1/KeeperRegistryLogicB2_1.sol
> +  }
within getConfig?

2023-06-06 11:05 UTC, infiloop2 commented on contracts/src/v0.8/dev/automation/2_1/KeeperRegistryBase2_1.sol
> +  mapping(uint256 => bytes) internal s_upkeepAdminOffchainConfig; // general config set by an administrative role
'admin' config is confusing here since there's already a concept of upkeep admin which is the end user