txm: clean up eth/evm prefixes
smartcontractkit/chainlink pull request #9451
Opened 2023-06-05 18:13 UTC by aalu1418

tickets: 
* https://smartcontract-it.atlassian.net/browse/BCI-1198
* https://smartcontract-it.atlassian.net/browse/BCI-1158

2023-06-06 15:37 UTC, samsondav requested changes
rename tables also?

2023-06-06 15:37 UTC, samsondav requested changes
rename tables also?

2023-06-06 16:24 UTC, aalu1418 commented
> rename tables also?

I think renaming the tables might be too much for this PR - and also there are ongoing conversations about the persistence layer so I think it would be best to minimize the changes for now

2023-06-06 21:42 UTC, prashantkumar1982 commented on common/txmgr/types/tx_store.go
> +	SaveInsufficientAttempt(timeout time.Duration, attempt *TxAttempt[CHAIN_ID, ADDR, TX_HASH, BLOCK_HASH, R, SEQ, FEE, ADD], broadcastAt time.Time) error
nit: SaveInsufficientFundsAttempt?
InsufficientAttempt seems a little confusing

2023-06-06 21:44 UTC, prashantkumar1982 commented on common/txmgr/types/tx_store.go
> +	UpdateKeyNextNonce(newNextNonce, currentNextNonce SEQ, address ADDR, chainID CHAIN_ID, qopts ...pg.QOpt) error
nit: rename all nonces to sequence

2023-06-06 21:45 UTC, prashantkumar1982 commented on core/chains/evm/txmgr/nonce_syncer.go
Maybe another PR, but NonceSyncer should be SequenceSyncer

2023-06-07 13:21 UTC, aalu1418 commented on core/chains/evm/txmgr/nonce_syncer.go
ah right - good reminder: I will address in a separate ticket: https://smartcontract-it.atlassian.net/browse/BCI-1404

2023-06-07 13:49 UTC, jmank88 approved these changes

2023-06-07 16:46 UTC, prashantkumar1982 approved these changes

2023-06-07 20:26 UTC, prashantkumar1982 approved these changes

2023-06-07 22:03 UTC, merged